import Link from "next/link";
import Image from "next/image";
import { notFound, redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/app/lib/prisma";
import { AccountHeader } from "@/app/components/account-header";
import { formatPrice } from "@/app/lib/products";
import { OrderTracking } from "@/app/components/order-tracking";
import { ORDER_STATUS_LABELS, orderStatusTone } from "@/app/lib/order-status";
import { PAYMENT_STATUS_LABELS, REFUND_STATUS_LABELS } from "@/app/lib/finance-labels";
import { CustomerOrderActions } from "@/app/components/customer-order-actions";
import { CustomerShipments } from "@/app/components/customer-shipments";

export default async function OrderDetailPage({ params }: PageProps<"/hesabim/siparisler/[id]">) {
  const session = await auth(); if (!session?.user?.id) redirect("/giris"); const { id } = await params;
  const order = await prisma.order.findFirst({ where: { id, userId: session.user.id }, select: { orderNumber: true, status: true, totalAmount: true, recipientName: true, address: true, district: true, city: true, postalCode: true, createdAt: true, payment: { select: { status: true } }, refunds: { select: { id: true, orderItemId: true, amount: true, status: true, requestedAt: true, completedAt: true } }, shipments: { orderBy: { createdAt: "asc" }, select: { id: true, status: true, carrierCode: true, carrierName: true, trackingNumber: true, seller: { select: { storeName: true } }, items: { select: { quantity: true, orderItem: { select: { productName: true } } } } } }, items: { orderBy: { createdAt: "asc" }, select: { id: true, productName: true, productSku: true, productImageUrl: true, unitPrice: true, quantity: true, status: true, shippingCompany: true, trackingNumber: true, seller: { select: { id: true, storeName: true } } } } } });
  if (!order) notFound(); const groups = Map.groupBy(order.items, (item) => item.seller.id);
  return <main className="min-h-screen bg-slate-50"><AccountHeader /><section className="mx-auto max-w-5xl px-5 py-10"><Link href="/hesabim/siparisler" className="text-sm font-bold text-sky-600">← Siparişlerim</Link><div className="mt-5 rounded-2xl border bg-white p-6 shadow-sm"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-sm text-slate-500">Sipariş numarası</p><h1 className="text-2xl font-black">{order.orderNumber}</h1><p className="mt-1 text-xs text-slate-500">{new Intl.DateTimeFormat("tr-TR", { dateStyle: "long", timeStyle: "short" }).format(order.createdAt)}</p></div><span className={`h-fit rounded-full px-3 py-2 text-xs font-black ring-1 ${orderStatusTone(order.status)}`}>{ORDER_STATUS_LABELS[order.status]}</span></div><div className="mt-4 rounded-xl bg-slate-50 p-4 text-sm"><b>Ödeme:</b> {order.payment ? PAYMENT_STATUS_LABELS[order.payment.status] : "Ödeme kaydı yok"} · <b>İade:</b> {order.refunds.length ? order.refunds.map((refund) => REFUND_STATUS_LABELS[refund.status]).join(", ") : "Yok"}</div><CustomerShipments shipments={order.shipments} /><div className="mt-6 space-y-6">{Array.from(groups.values()).map((items) => <section key={items[0].seller.id} className="rounded-2xl border p-5"><h2 className="font-black">{items[0].seller.storeName}</h2><OrderTracking statuses={items.map((item) => item.status)} /><div className="mt-5 space-y-4 border-t pt-5">{items.map((item) => { const refund = order.refunds.find((entry) => entry.orderItemId === item.id); return <div key={item.id} className="flex gap-4"><div className="relative h-16 w-16 shrink-0 overflow-hidden rounded-xl bg-slate-100"><Image src={item.productImageUrl} alt={item.productName} fill className="object-contain p-1" /></div><div className="min-w-0 flex-1"><b>{item.productName}</b><p className="text-xs text-slate-500">SKU: {item.productSku ?? "—"} · {item.quantity} adet · {ORDER_STATUS_LABELS[item.status]}</p>{refund ? <p className="mt-2 text-xs font-bold text-violet-700">İade: {REFUND_STATUS_LABELS[refund.status]} · {formatPrice(Number(refund.amount))}</p> : <CustomerOrderActions itemId={item.id} status={item.status} />}</div><b>{formatPrice(Number(item.unitPrice) * item.quantity)}</b></div>; })}</div></section>)}</div><div className="mt-6 border-t pt-5"><p className="font-black">Toplam: {formatPrice(Number(order.totalAmount))}</p><p className="mt-4 text-sm text-slate-600">Teslimat: {order.recipientName}, {order.address}, {order.district}/{order.city}{order.postalCode ? ` · ${order.postalCode}` : ""}</p></div></div></section></main>;
}
