import Link from "next/link";
import type { PaymentStatus, PayoutStatus, RefundStatus } from "@prisma/client";
import { AdminShell } from "@/app/components/admin-shell";
import { requireAdmin } from "@/app/lib/admin-auth";
import { prisma } from "@/app/lib/prisma";
import { formatPrice } from "@/app/lib/products";
import { PAYMENT_STATUS_LABELS, PAYOUT_STATUS_LABELS, REFUND_STATUS_LABELS } from "@/app/lib/finance-labels";
import { AdminRefundActions } from "@/app/components/admin-refund-actions";

const PAGE_SIZE = 20;
type FinanceRow = { id: string; createdAt?: Date; requestedAt?: Date; order: { orderNumber: string }; seller?: { storeName: string }; provider?: string; amount?: { toString(): string }; netAmount?: { toString(): string }; currency: string; status: PaymentStatus | PayoutStatus | RefundStatus; providerPaymentId?: string | null; providerRefundId?: string | null; reason?: string; orderItem?: { productName: string } };
export default async function AdminFinancePage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin(); const params = await searchParams; const value = (key: string) => typeof params[key] === "string" ? params[key] : "";
  const type = ["payments", "refunds", "payouts"].includes(value("type")) ? value("type") : "payments";
  const q = value("q").trim().slice(0, 120); const status = value("status").slice(0, 40); const page = Math.max(1, Math.min(10_000, Number.parseInt(value("page"), 10) || 1));
  const [paymentPending, refundPending, payoutPending] = await Promise.all([prisma.payment.count({ where: { status: "PENDING" } }), prisma.refund.count({ where: { status: { in: ["REQUESTED", "APPROVED", "PROCESSING"] } } }), prisma.sellerPayout.count({ where: { status: { in: ["PENDING", "BLOCKED", "AVAILABLE", "SCHEDULED"] } } })]);
  let total = 0; let content;
  if (type === "refunds") {
    const valid = ["REQUESTED", "APPROVED", "PROCESSING", "COMPLETED", "REJECTED", "FAILED", "CANCELLED"].includes(status) ? status as RefundStatus : undefined;
    const where = { ...(valid ? { status: valid } : {}), ...(q ? { OR: [{ order: { orderNumber: { contains: q, mode: "insensitive" as const } } }, { seller: { storeName: { contains: q, mode: "insensitive" as const } } }, { providerRefundId: { contains: q, mode: "insensitive" as const } }] } : {}) };
    [total, content] = await Promise.all([prisma.refund.count({ where }), prisma.refund.findMany({ where, select: { id: true, amount: true, currency: true, status: true, reason: true, providerRefundId: true, requestedAt: true, order: { select: { orderNumber: true } }, seller: { select: { storeName: true } }, orderItem: { select: { productName: true } } }, orderBy: { requestedAt: "desc" }, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE })]);
  } else if (type === "payouts") {
    const valid = ["PENDING", "BLOCKED", "AVAILABLE", "SCHEDULED", "PAID", "CANCELLED"].includes(status) ? status as PayoutStatus : undefined;
    const where = { ...(valid ? { status: valid } : {}), ...(q ? { OR: [{ order: { orderNumber: { contains: q, mode: "insensitive" as const } } }, { seller: { storeName: { contains: q, mode: "insensitive" as const } } }] } : {}) };
    [total, content] = await Promise.all([prisma.sellerPayout.count({ where }), prisma.sellerPayout.findMany({ where, select: { id: true, grossAmount: true, commissionAmount: true, netAmount: true, currency: true, status: true, createdAt: true, order: { select: { orderNumber: true } }, seller: { select: { storeName: true } }, orderItem: { select: { productName: true } } }, orderBy: { createdAt: "desc" }, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE })]);
  } else {
    const valid = ["PENDING", "AUTHORIZED", "PAID", "FAILED", "CANCELLED", "REFUNDED", "PARTIALLY_REFUNDED"].includes(status) ? status as PaymentStatus : undefined;
    const where = { ...(valid ? { status: valid } : {}), ...(q ? { OR: [{ order: { orderNumber: { contains: q, mode: "insensitive" as const } } }, { providerPaymentId: { contains: q, mode: "insensitive" as const } }, { provider: { contains: q, mode: "insensitive" as const } }] } : {}) };
    [total, content] = await Promise.all([prisma.payment.count({ where }), prisma.payment.findMany({ where, select: { id: true, amount: true, currency: true, status: true, provider: true, providerPaymentId: true, createdAt: true, updatedAt: true, order: { select: { orderNumber: true } } }, orderBy: { createdAt: "desc" }, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE })]);
  }
  const pages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  const rows = content as unknown as FinanceRow[];
  return <AdminShell title="Finans Operasyonları"><div className="grid gap-4 sm:grid-cols-3"><Card label="Bekleyen ödeme" value={paymentPending} /><Card label="Açık iade" value={refundPending} /><Card label="Bekleyen hakediş" value={payoutPending} /></div><nav className="mt-6 flex flex-wrap gap-2">{[["payments", "Ödemeler"], ["refunds", "İadeler"], ["payouts", "Hakedişler"]].map(([key, label]) => <Link key={key} href={`?type=${key}`} className={`rounded-xl px-4 py-2 text-sm font-bold ${type === key ? "bg-sky-600 text-white" : "border bg-white"}`}>{label}</Link>)}</nav><form className="mt-4 flex flex-wrap gap-3"><input type="hidden" name="type" value={type} /><input name="q" defaultValue={q} placeholder="Sipariş, mağaza veya provider referansı" className="min-w-72 flex-1 rounded-xl border bg-white p-3 text-sm" /><input name="status" defaultValue={status} placeholder="Durum" className="rounded-xl border bg-white p-3 text-sm" /><button className="rounded-xl bg-slate-950 px-5 text-sm font-black text-white">Filtrele</button></form><div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="min-w-[900px] w-full text-left text-sm"><thead className="bg-slate-50"><tr><th className="p-4">Tarih</th><th>Sipariş</th><th>Taraf / Provider</th><th>Tutar</th><th>Durum</th><th>Referans / Açıklama</th></tr></thead><tbody>{rows.length ? rows.map((row) => <tr key={row.id} className="border-t"><td className="p-4">{new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short" }).format(row.createdAt ?? row.requestedAt)}</td><td>{row.order.orderNumber}</td><td>{row.seller?.storeName ?? row.provider}</td><td>{formatPrice(Number(row.amount ?? row.netAmount))} {row.currency}</td><td>{row.provider ? PAYMENT_STATUS_LABELS[row.status as PaymentStatus] : row.reason ? REFUND_STATUS_LABELS[row.status as RefundStatus] : PAYOUT_STATUS_LABELS[row.status as PayoutStatus]}{type === "refunds" && <AdminRefundActions refundId={row.id} status={row.status} />}</td><td className="max-w-xs truncate">{row.providerPaymentId ?? row.providerRefundId ?? row.reason ?? row.orderItem?.productName ?? "—"}</td></tr>) : <tr><td colSpan={6} className="p-8 text-center text-slate-500">Kayıt bulunamadı.</td></tr>}</tbody></table></div>{pages > 1 && <nav className="mt-5 flex justify-center gap-3"><Link href={`?type=${type}&page=${Math.max(1, page - 1)}&q=${encodeURIComponent(q)}&status=${status}`} className="rounded-xl border bg-white px-4 py-2">Önceki</Link><span className="py-2 text-sm">{page} / {pages}</span><Link href={`?type=${type}&page=${Math.min(pages, page + 1)}&q=${encodeURIComponent(q)}&status=${status}`} className="rounded-xl border bg-white px-4 py-2">Sonraki</Link></nav>}<p className="mt-5 text-sm text-slate-500">İade onayı yalnızca operasyonel karardır; gerçek provider refund’u yapılmaz. Ödeme ve payout durumları provider olmadan değiştirilemez.</p></AdminShell>;
}
function Card({ label, value }: { label: string; value: number }) { return <section className="rounded-2xl border bg-white p-5"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-black">{value}</p></section>; }
