import type { Prisma } from "@prisma/client";

export const customerOrderSelect = {
  id: true,
  orderNumber: true,
  totalAmount: true,
  subtotalAmount: true,
  discountAmount: true,
  couponCode: true,
  status: true,
  recipientName: true,
  phone: true,
  city: true,
  district: true,
  address: true,
  postalCode: true,
  createdAt: true,
  updatedAt: true,
  payment: { select: { status: true } },
  shipments: {
    orderBy: { createdAt: "asc" },
    select: {
      id: true, status: true, carrierCode: true, carrierName: true, trackingNumber: true,
      preparedAt: true, shippedAt: true, deliveredAt: true, estimatedDeliveryAt: true,
      seller: { select: { id: true, storeName: true, storeSlug: true } },
      items: { select: { quantity: true, orderItem: { select: { id: true, productName: true, productSku: true, productImageUrl: true, unitPrice: true, status: true } } } },
    },
  },
  items: {
    select: {
      id: true,
      productId: true,
      productName: true,
      productSku: true,
      productImageUrl: true,
      unitPrice: true,
      quantity: true,
      status: true,
      shippingCompany: true,
      trackingNumber: true,
      createdAt: true,
      updatedAt: true,
      seller: { select: { id: true, storeName: true, storeSlug: true } },
    },
  },
} satisfies Prisma.OrderSelect;
