import "server-only";
import { Prisma, type PrismaClient, type InstallmentCommercialPolicyScope } from "@prisma/client";
import { prisma } from "./prisma";
import { parseInstallmentSet, SellerInstallmentControlError } from "./seller-installment-control";

export type CommercialPolicyErrorCode="FORBIDDEN"|"INVALID_SCOPE"|"TARGET_NOT_FOUND"|"INVALID_AMOUNT_BAND"|"INVALID_WINDOW"|"INVALID_REASON"|"INVALID_ALLOWED_INSTALLMENTS"|"OVERLAPPING_POLICY"|"AMBIGUOUS_POLICY"|"STALE_VERSION"|"CONCURRENT_CHANGE"|"REQUEST_PROVENANCE";
export class CommercialPolicyError extends Error{constructor(readonly code:CommercialPolicyErrorCode){super(code)}}
type Host=Pick<PrismaClient,"$transaction">; const SCOPES=Object.freeze(["GLOBAL","SELLER","CATEGORY","SELLER_CATEGORY","SELLER_OFFER"] as const);
const dec=(raw:unknown)=>{try{const x=new Prisma.Decimal(raw as string);if(!x.isFinite()||x.isNegative())throw 0;return x}catch{throw new CommercialPolicyError("INVALID_AMOUNT_BAND")}};
const why=(raw:unknown)=>{if(typeof raw!=="string"||raw.trim().length<3||raw.trim().length>500)throw new CommercialPolicyError("INVALID_REASON");return raw.trim()};
const set=(raw:unknown)=>{try{return parseInstallmentSet(raw)}catch(e){if(e instanceof SellerInstallmentControlError)throw new CommercialPolicyError("INVALID_ALLOWED_INSTALLMENTS");throw e}};
const ver=(raw:unknown)=>{if(!Number.isInteger(raw)||(raw as number)<1)throw new CommercialPolicyError("STALE_VERSION");return raw as number};
const serial=(e:unknown)=>e instanceof Prisma.PrismaClientKnownRequestError&&(e.code==="P2034"||(e.code==="P2010"&&JSON.stringify(e.meta??{}).includes("40001")));
export function normalizePolicyScope(input:Readonly<{scopeType:unknown;sellerId?:string|null;categoryId?:string|null;sellerOfferId?:string|null}>){const s=input.scopeType;if(typeof s!=="string"||!SCOPES.includes(s as typeof SCOPES[number]))throw new CommercialPolicyError("INVALID_SCOPE");const scope=s as InstallmentCommercialPolicyScope;let key:string;switch(scope){case"GLOBAL":if(input.sellerId||input.categoryId||input.sellerOfferId)throw new CommercialPolicyError("INVALID_SCOPE");key="GLOBAL";break;case"SELLER":if(!input.sellerId||input.categoryId||input.sellerOfferId)throw new CommercialPolicyError("INVALID_SCOPE");key=`SELLER:${input.sellerId}`;break;case"CATEGORY":if(!input.categoryId||input.sellerId||input.sellerOfferId)throw new CommercialPolicyError("INVALID_SCOPE");key=`CATEGORY:${input.categoryId}`;break;case"SELLER_CATEGORY":if(!input.sellerId||!input.categoryId||input.sellerOfferId)throw new CommercialPolicyError("INVALID_SCOPE");key=`SELLER_CATEGORY:${input.sellerId}:${input.categoryId}`;break;default:if(!input.sellerOfferId||!input.sellerId||input.categoryId)throw new CommercialPolicyError("INVALID_SCOPE");key=`SELLER_OFFER:${input.sellerOfferId}`;}return {scopeType:scope,scopeKey:key,sellerId:input.sellerId??null,categoryId:input.categoryId??null,sellerOfferId:input.sellerOfferId??null} as const}
function values(i:Readonly<{minimumEligibleAmount:unknown;maximumEligibleAmount?:unknown;effectiveFrom:Date;effectiveUntil?:Date|null;reason:unknown;allowedInstallments:unknown}>){const min=dec(i.minimumEligibleAmount),max=i.maximumEligibleAmount==null?null:dec(i.maximumEligibleAmount);if(max&&max.lessThanOrEqualTo(min))throw new CommercialPolicyError("INVALID_AMOUNT_BAND");if(!(i.effectiveFrom instanceof Date)||Number.isNaN(i.effectiveFrom.getTime())||(i.effectiveUntil&&(!(i.effectiveUntil instanceof Date)||Number.isNaN(i.effectiveUntil.getTime())||i.effectiveUntil<=i.effectiveFrom)))throw new CommercialPolicyError("INVALID_WINDOW");return {allowed:[...set(i.allowedInstallments)],minimumEligibleAmount:min,maximumEligibleAmount:max,effectiveFrom:i.effectiveFrom,effectiveUntil:i.effectiveUntil??null,reason:why(i.reason)}}
function overlapWhere(scopeKey:string,v:ReturnType<typeof values>,excludeId?:string):Prisma.InstallmentCommercialPolicyWhereInput{return{scopeKey,...(excludeId?{id:{not:excludeId}}:{}),AND:[{minimumEligibleAmount:{lt:v.maximumEligibleAmount??new Prisma.Decimal("999999999999.99")}},{OR:[{maximumEligibleAmount:null},{maximumEligibleAmount:{gt:v.minimumEligibleAmount}}]},{effectiveFrom:{lt:v.effectiveUntil??new Date("9999-12-31T23:59:59.999Z")}},{OR:[{effectiveUntil:null},{effectiveUntil:{gt:v.effectiveFrom}}]}]}}
async function lockScope(tx:Prisma.TransactionClient,scopeKey:string){await tx.$queryRaw`SELECT 1 FROM (SELECT pg_advisory_xact_lock(hashtext(${scopeKey}))) AS lock_result`}
type PolicyStateInput={scopeType:InstallmentCommercialPolicyScope;scopeKey:string;sellerId:string|null;categoryId:string|null;sellerOfferId:string|null;allowedInstallments:Prisma.JsonValue;minimumEligibleAmount:{toString():string};maximumEligibleAmount:{toString():string}|null;effectiveFrom:Date;effectiveUntil:Date|null;version:number;approvedFromRequestId:string|null}
function state(p:PolicyStateInput){return{scopeType:p.scopeType,scopeKey:p.scopeKey,sellerId:p.sellerId,categoryId:p.categoryId,sellerOfferId:p.sellerOfferId,allowedInstallments:set(p.allowedInstallments),minimumEligibleAmount:p.minimumEligibleAmount.toString(),maximumEligibleAmount:p.maximumEligibleAmount?.toString()??null,effectiveFrom:p.effectiveFrom,effectiveUntil:p.effectiveUntil,version:p.version,approvedFromRequestId:p.approvedFromRequestId}}
export async function createInstallmentCommercialPolicy(i:Readonly<{actorUserId:string;scopeType:unknown;sellerId?:string|null;categoryId?:string|null;sellerOfferId?:string|null;allowedInstallments:unknown;minimumEligibleAmount:unknown;maximumEligibleAmount?:unknown;effectiveFrom:Date;effectiveUntil?:Date|null;approvedFromRequestId?:string|null;reason:unknown}>,client:Host=prisma){const scope=normalizePolicyScope(i),v=values(i);try{return await client.$transaction(async tx=>{const a=await tx.user.findUnique({where:{id:i.actorUserId},select:{role:true}});if(a?.role!=="ADMIN")throw new CommercialPolicyError("FORBIDDEN");if(scope.sellerId&&!await tx.sellerProfile.findUnique({where:{id:scope.sellerId},select:{id:true}})||scope.categoryId&&!await tx.category.findUnique({where:{id:scope.categoryId},select:{id:true}})||scope.sellerOfferId&&!await tx.sellerOffer.findFirst({where:{id:scope.sellerOfferId,sellerId:scope.sellerId!},select:{id:true}}))throw new CommercialPolicyError("TARGET_NOT_FOUND");if(i.approvedFromRequestId){const r=await tx.sellerInstallmentRequest.findUnique({where:{id:i.approvedFromRequestId},select:{status:true,sellerId:true,scopeType:true,sellerOfferId:true,approvedAllowedInstallments:true}});if(!r||r.status!=="APPROVED"||(scope.scopeType==="SELLER_OFFER"&&r.scopeType!=="SELLER_OFFER")||r.sellerId!==scope.sellerId||r.sellerOfferId!==scope.sellerOfferId||set(r.approvedAllowedInstallments).some((x)=>!v.allowed.includes(x))||v.allowed.some((x)=>!set(r.approvedAllowedInstallments).includes(x)))throw new CommercialPolicyError("REQUEST_PROVENANCE")}await lockScope(tx,scope.scopeKey);if(await tx.installmentCommercialPolicy.findFirst({where:overlapWhere(scope.scopeKey,v),select:{id:true}}))throw new CommercialPolicyError("OVERLAPPING_POLICY");const p=await tx.installmentCommercialPolicy.create({data:{...scope,allowedInstallments:v.allowed,minimumEligibleAmount:v.minimumEligibleAmount,maximumEligibleAmount:v.maximumEligibleAmount,effectiveFrom:v.effectiveFrom,effectiveUntil:v.effectiveUntil,approvedFromRequestId:i.approvedFromRequestId??null,reason:v.reason,createdByUserId:i.actorUserId}});const n=state(p);await tx.installmentCommercialPolicyAudit.create({data:{policyId:p.id,actorUserId:i.actorUserId,actorRole:a.role,action:"POLICY_CREATED",newState:n,newVersion:1,reason:v.reason}});return p},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}catch(e){if(serial(e))throw new CommercialPolicyError("CONCURRENT_CHANGE");throw e}}
export async function getEffectiveInstallmentCommercialPolicy(i:Readonly<{scopeKey:string;amount:unknown;at:Date}>,client:Pick<PrismaClient,"installmentCommercialPolicy">=prisma){const amount=dec(i.amount),rows=await client.installmentCommercialPolicy.findMany({where:{scopeKey:i.scopeKey,minimumEligibleAmount:{lte:amount},AND:[{OR:[{maximumEligibleAmount:null},{maximumEligibleAmount:{gt:amount}}]},{effectiveFrom:{lte:i.at}},{OR:[{effectiveUntil:null},{effectiveUntil:{gt:i.at}}]}]},orderBy:[{effectiveFrom:"desc"},{id:"asc"}],take:2});if(rows.length>1)throw new CommercialPolicyError("AMBIGUOUS_POLICY");return rows[0]??null}

export async function updateInstallmentCommercialPolicy(i:Readonly<{actorUserId:string;policyId:string;expectedVersion:unknown;allowedInstallments:unknown;minimumEligibleAmount:unknown;maximumEligibleAmount?:unknown;effectiveFrom:Date;effectiveUntil?:Date|null;reason:unknown}>,client:Host=prisma){const expected=ver(i.expectedVersion),v=values(i);try{return await client.$transaction(async tx=>{const a=await tx.user.findUnique({where:{id:i.actorUserId},select:{role:true}});if(a?.role!=="ADMIN")throw new CommercialPolicyError("FORBIDDEN");await tx.$queryRaw`SELECT "id" FROM "InstallmentCommercialPolicy" WHERE "id"=${i.policyId} FOR UPDATE`;const cur=await tx.installmentCommercialPolicy.findUnique({where:{id:i.policyId}});if(!cur)throw new CommercialPolicyError("TARGET_NOT_FOUND");if(cur.version!==expected)throw new CommercialPolicyError("STALE_VERSION");if(await tx.installmentCommercialPolicy.findFirst({where:overlapWhere(cur.scopeKey,v,cur.id),select:{id:true}}))throw new CommercialPolicyError("OVERLAPPING_POLICY");const changed=await tx.installmentCommercialPolicy.updateMany({where:{id:cur.id,version:expected},data:{allowedInstallments:v.allowed,minimumEligibleAmount:v.minimumEligibleAmount,maximumEligibleAmount:v.maximumEligibleAmount,effectiveFrom:v.effectiveFrom,effectiveUntil:v.effectiveUntil,reason:v.reason,version:{increment:1}}});if(changed.count!==1)throw new CommercialPolicyError("STALE_VERSION");const p=await tx.installmentCommercialPolicy.findUniqueOrThrow({where:{id:cur.id}});await tx.installmentCommercialPolicyAudit.create({data:{policyId:p.id,actorUserId:i.actorUserId,actorRole:a.role,action:"POLICY_UPDATED",previousState:state(cur),newState:state(p),expectedVersion:expected,previousVersion:cur.version,newVersion:p.version,reason:v.reason}});return p},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}catch(e){if(serial(e))throw new CommercialPolicyError("CONCURRENT_CHANGE");throw e}}
