import type { SellerOnboardingStatus } from "@prisma/client";
import { z } from "zod";

export const kybDocumentInputSchema = z.object({ type: z.enum(["TAX_CERTIFICATE", "TRADE_REGISTRY", "IDENTITY_DOCUMENT", "SIGNATURE_CIRCULAR", "OTHER"]), reference: z.string().trim().min(3).max(500), fileName: z.string().trim().min(1).max(191).optional() }).strict();
export const sellerOnboardingDraftSchema = z.object({ storeName: z.string().trim().min(2).max(191), legalName: z.string().trim().min(2).max(191), companyType: z.string().trim().min(2).max(100), taxNumber: z.string().trim().min(5).max(32), taxOffice: z.string().trim().min(2).max(100), city: z.string().trim().min(2).max(100), address: z.string().trim().min(10).max(1000), description: z.string().trim().min(20).max(2000), categories: z.string().trim().min(2).max(500), phone: z.string().trim().min(10).max(30), authorizedPersonName: z.string().trim().min(2).max(100), authorizedPersonSurname: z.string().trim().min(2).max(100), authorizedPersonEmail: z.string().trim().email().max(191), authorizedPersonTitle: z.string().trim().min(2).max(100), acceptedTerms: z.literal(true), documents: z.array(kybDocumentInputSchema).max(10) }).strict().refine((value) => new Set(value.documents.map((document) => document.type)).size === value.documents.length, { path: ["documents"], message: "Aynı belge türü birden fazla kez gönderilemez." });
export type SellerOnboardingDraftInput = z.infer<typeof sellerOnboardingDraftSchema>;
export type SellerOnboardingReviewAction = "START_REVIEW" | "REQUEST_REVISION" | "APPROVE" | "REJECT";
export class SellerOnboardingError extends Error { constructor(public readonly code: "NOT_FOUND" | "FORBIDDEN" | "INVALID_STATE" | "INCOMPLETE" | "CONFLICT", message: string) { super(message); } }
export const requiredDocumentTypes = ["TAX_CERTIFICATE", "IDENTITY_DOCUMENT"] as const;
export function assertSubmissionComplete(input: SellerOnboardingDraftInput) { const supplied = new Set(input.documents.map((document) => document.type)); if (requiredDocumentTypes.some((type) => !supplied.has(type))) throw new SellerOnboardingError("INCOMPLETE", "Vergi levhası ve yetkili kimlik belge referansı zorunludur."); }
export function nextReviewStatus(current: SellerOnboardingStatus, action: SellerOnboardingReviewAction): SellerOnboardingStatus { const allowed: Record<SellerOnboardingReviewAction, Partial<Record<SellerOnboardingStatus, SellerOnboardingStatus>>> = { START_REVIEW: { SUBMITTED: "UNDER_REVIEW", UNDER_REVIEW: "UNDER_REVIEW" }, REQUEST_REVISION: { SUBMITTED: "NEEDS_REVISION", UNDER_REVIEW: "NEEDS_REVISION", NEEDS_REVISION: "NEEDS_REVISION" }, APPROVE: { SUBMITTED: "APPROVED", UNDER_REVIEW: "APPROVED", APPROVED: "APPROVED" }, REJECT: { SUBMITTED: "REJECTED", UNDER_REVIEW: "REJECTED", REJECTED: "REJECTED" } }; const target = allowed[action][current]; if (!target) throw new SellerOnboardingError("INVALID_STATE", `${current} durumunda ${action} işlemi yapılamaz.`); return target; }
