"use client";
import { useState } from "react";

type Status = "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "NEEDS_REVISION" | "APPROVED" | "REJECTED";
type Application = { id: string; storeName: string; legalName: string; companyType: string; phone: string; taxNumber: string; taxOffice: string; city: string; address: string; categories: string; description: string; onboardingStatus: Status; revisionReason: string | null; activationEligible: boolean; createdAt: string; submittedAt: string | null; authorizedPersonName: string; authorizedPersonSurname: string; authorizedPersonEmail: string; authorizedPersonTitle: string; kybDocuments: { type: string; status: string }[]; user: { name: string; surname: string; email: string; phone: string } };

export function AdminApplicationsTable({ initialApplications }: { initialApplications: Application[] }) {
  const [items, setItems] = useState(initialApplications); const [reason, setReason] = useState<Record<string, string>>({}); const [busy, setBusy] = useState<string | null>(null);
  async function act(id: string, action: "start_review" | "request_revision" | "approve" | "reject") {
    const note = reason[id]?.trim(); if ((action === "request_revision" || action === "reject") && !note) return window.alert("İşlem nedeni girin.");
    setBusy(id); const response = await fetch(`/api/admin/seller-applications/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json", "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify(action === "request_revision" || action === "reject" ? { action, reason: note } : { action }) }); const body = await response.json().catch(() => ({})) as { onboardingStatus?: Status; error?: string }; setBusy(null);
    if (!response.ok) return window.alert(body.error ?? "İşlem tamamlanamadı.");
    setItems((current) => current.map((item) => item.id === id ? { ...item, onboardingStatus: body.onboardingStatus!, activationEligible: body.onboardingStatus === "APPROVED", revisionReason: action === "request_revision" ? note ?? null : null } : item));
  }
  return <div className="space-y-4">{items.map((item) => <article key={item.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 lg:flex-row lg:justify-between"><div><div className="flex items-center gap-3"><h2 className="text-xl font-black">{item.storeName}</h2><span className="rounded-full bg-sky-50 px-3 py-1 text-xs font-bold text-sky-700">{item.onboardingStatus}</span></div><p className="mt-2 text-sm font-semibold">{item.legalName} · {item.authorizedPersonName} {item.authorizedPersonSurname} ({item.authorizedPersonTitle})</p><p className="mt-1 text-sm text-slate-500">{item.authorizedPersonEmail} · {item.phone || item.user.phone} · {item.companyType} · {item.city}</p><p className="mt-3 text-sm text-slate-600">{item.categories}</p><details className="mt-3 text-sm text-slate-500"><summary className="cursor-pointer font-bold">KYB ayrıntıları</summary><p className="mt-2">{item.taxNumber} · {item.taxOffice}<br />{item.address}<br />Belgeler: {item.kybDocuments.map((document) => `${document.type} (${document.status})`).join(", ") || "Yok"}</p></details></div>{["SUBMITTED", "UNDER_REVIEW"].includes(item.onboardingStatus) && <div className="min-w-64 space-y-2">{item.onboardingStatus === "SUBMITTED" && <button disabled={busy === item.id} onClick={() => act(item.id, "start_review")} className="w-full rounded-xl border px-4 py-3 text-sm font-bold">İncelemeye Al</button>}<button disabled={busy === item.id} onClick={() => act(item.id, "approve")} className="w-full rounded-xl bg-green-600 px-4 py-3 text-sm font-bold text-white">KYB Onayla</button><input value={reason[item.id] ?? ""} onChange={(event) => setReason((current) => ({ ...current, [item.id]: event.target.value }))} placeholder="Revizyon / ret nedeni" className="w-full rounded-xl border px-3 py-2.5 text-sm" /><button disabled={busy === item.id} onClick={() => act(item.id, "request_revision")} className="w-full rounded-xl bg-amber-50 px-4 py-3 text-sm font-bold text-amber-700">Revizyon İste</button><button disabled={busy === item.id} onClick={() => act(item.id, "reject")} className="w-full rounded-xl bg-red-50 px-4 py-3 text-sm font-bold text-red-600">Reddet</button></div>}</div></article>)}</div>;
}
