"use client";
import Link from "next/link";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { useCart } from "./cart-context";
import { formatPrice } from "@/app/lib/products";
export function CheckoutForm({ defaultName }: { defaultName: string }) { const router = useRouter(); const { items, subtotal, isLoaded, clearCart } = useCart(); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!items.length) return setError("Sepetiniz boş."); setSaving(true); setError(""); try { const form = new FormData(event.currentTarget); const response = await fetch("/api/orders", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ clientRequestId: crypto.randomUUID(), address: Object.fromEntries(form), items: items.map((item) => ({ productId: item.id, quantity: item.quantity })) }) }); const result = await response.json().catch(() => ({})) as { id?: string; error?: string }; if (!response.ok || !result.id) { setError(result.error ?? "Sipariş işlemi tamamlanamadı. Lütfen tekrar deneyin."); return; } clearCart(); router.replace(`/hesabim/siparisler/${result.id}`); } catch { setError("Bağlantı kurulamadı. Lütfen tekrar deneyin."); } finally { setSaving(false); } }
 if (!isLoaded) return <main className="min-h-screen bg-slate-50 p-10 text-center">Sepet hazırlanıyor...</main>;
 return <main className="min-h-screen bg-slate-50 px-5 py-10 text-slate-900"><div className="mx-auto grid max-w-5xl gap-8 lg:grid-cols-[1fr_330px]"><form onSubmit={submit} className="rounded-3xl border bg-white p-6 shadow-sm sm:p-8"><Link href="/sepet" className="text-sm font-bold text-sky-600">← Sepete dön</Link><p className="mt-6 text-sm font-bold text-sky-600">TESLİMAT BİLGİLERİ</p><h1 className="mt-1 text-3xl font-black">Siparişini tamamla</h1><div className="mt-7 grid gap-4 sm:grid-cols-2">{[["recipientName","Ad soyad",defaultName],["phone","Telefon",""] ,["city","İl",""] ,["district","İlçe",""]].map(([name,label,value]) => <label key={name} className="text-sm font-bold">{label}<input required name={name} defaultValue={value} className="mt-2 w-full rounded-xl border px-4 py-3" /></label>)}<label className="text-sm font-bold sm:col-span-2">Mahalle ve açık adres<textarea required name="address" minLength={10} rows={4} className="mt-2 w-full rounded-xl border px-4 py-3" /></label><label className="text-sm font-bold">Posta kodu <span className="font-normal text-slate-400">(opsiyonel)</span><input name="postalCode" className="mt-2 w-full rounded-xl border px-4 py-3" /></label></div><div className="mt-6 rounded-2xl bg-sky-50 p-4 text-sm text-sky-900"><b>Test Siparişi</b><br />Ödeme entegrasyonu yakında. Bu adım stok ve sipariş kaydını test amaçlı tamamlar.</div>{error && <p className="mt-4 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-600">{error}</p>}<button disabled={saving || !items.length} className="mt-6 w-full rounded-xl bg-sky-500 py-4 font-bold text-white disabled:opacity-50">{saving ? "Sipariş oluşturuluyor..." : "Siparişi Ver"}</button></form><aside className="h-fit rounded-3xl border bg-white p-6 shadow-sm"><h2 className="text-xl font-black">Sipariş özeti</h2><div className="mt-5 space-y-3">{items.map(item => <div key={item.id} className="flex justify-between gap-3 text-sm"><span>{item.name} × {item.quantity}</span><b>{formatPrice(item.unitPrice * item.quantity)}</b></div>)}</div><div className="mt-5 border-t pt-5 text-lg font-black">Toplam: <span className="float-right">{formatPrice(subtotal)}</span></div></aside></div></main>; }
