import type { ShipmentStatus } from "@prisma/client";
import { canonicalShipmentStatus, type CanonicalShipmentStatus, shipmentStatusLabel, trackingUrlFor } from "@/app/lib/shipping";

type Shipment = { id: string; status: ShipmentStatus; carrierCode: string | null; carrierName: string | null; trackingNumber: string | null; seller: { storeName: string }; items: { quantity: number; orderItem: { productName: string } }[]; events: { id: string; status: ShipmentStatus; eventTime: Date; location: string | null; description: string | null }[] };
const journeySteps: CanonicalShipmentStatus[] = ["CREATED", "READY_FOR_SHIPMENT", "HANDED_TO_CARRIER", "IN_TRANSIT", "AT_TRANSFER_CENTER", "OUT_FOR_DELIVERY", "AT_PICKUP_POINT", "DELIVERED"];

export function CustomerShipments({ shipments }: { shipments: Shipment[] }) {
  if (!shipments.length) return null;
  return <section className="mt-6"><h2 className="text-lg font-black">Kargom nerede?</h2><p className="mt-1 text-sm text-slate-500">Her paket kendi taşıma durumu ve takip geçmişiyle gösterilir.</p><div className="mt-3 space-y-4">{shipments.map((shipment, index) => {
    const canonical = canonicalShipmentStatus(shipment.status); const current = journeySteps.indexOf(canonical); const url = trackingUrlFor(shipment.carrierCode, shipment.trackingNumber);
    return <article key={shipment.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><div><p className="text-xs font-black text-sky-600">PAKET {index + 1}</p><h3 className="font-black">{shipment.seller.storeName}</h3></div><span className="h-fit rounded-full bg-sky-50 px-3 py-2 text-sm font-black text-sky-700">{shipmentStatusLabel(shipment.status)}</span></div><p className="mt-3 text-sm text-slate-600">{shipment.items.map((item) => `${item.orderItem.productName} (${item.quantity} adet)`).join(", ")}</p>{shipment.carrierName && <div className="mt-4 rounded-xl bg-sky-50 p-4 text-sm"><b>{shipment.carrierName}</b><p className="mt-1 break-all">Takip no: {shipment.trackingNumber}</p>{url ? <a href={url} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex min-h-11 items-center rounded-xl bg-sky-600 px-4 font-black text-white">Kargomu takip et</a> : <p className="mt-2 text-xs font-semibold text-slate-500">Takip bağlantısı şu anda oluşturulamıyor; takip numaranızı kargo firmasında kullanabilirsiniz.</p>}</div>}<ol className="mt-5 grid gap-2 sm:grid-cols-4 lg:grid-cols-8">{journeySteps.map((step, stepIndex) => <li key={step} className={`rounded-xl p-3 text-xs font-bold ${current >= 0 && stepIndex <= current ? "bg-sky-50 text-sky-700" : "bg-slate-50 text-slate-400"}`}>{current >= 0 && stepIndex < current ? "✓ " : stepIndex === current ? "● " : "○ "}{shipmentStatusLabel(step)}</li>)}</ol>{shipment.events.length > 0 && <div className="mt-5 border-t pt-4"><h4 className="text-sm font-black">Gönderi geçmişi</h4><ol className="mt-3 space-y-3">{shipment.events.map((event) => <li key={event.id} className="border-l-2 border-sky-200 pl-3 text-sm"><b>{shipmentStatusLabel(event.status)}</b><p className="text-xs text-slate-500">{new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium", timeStyle: "short" }).format(event.eventTime)}{event.location ? ` · ${event.location}` : ""}</p>{event.description ? <p className="mt-1 text-slate-600">{event.description}</p> : null}</li>)}</ol></div>}</article>;
  })}</div></section>;
}
