"use client";
import { FormEvent, useEffect, useState } from "react";

type Review = { id: string; rating: number; comment: string; createdAt: string; user: { name: string } };
export function ProductReviews({ productId, rating, reviewCount }: { productId: string; rating: number; reviewCount: number }) {
  const [data, setData] = useState<{ reviews: Review[]; eligibleOrderItemId: string | null; alreadyReviewed: boolean } | null>(null); const [message, setMessage] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { let active = true; fetch(`/api/reviews?productId=${encodeURIComponent(productId)}`).then((response)=>response.json()).then((value)=>{if(active)setData(value)}).catch(()=>{if(active)setMessage("Yorumlar yüklenemedi.")}); return()=>{active=false}; }, [productId]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!data?.eligibleOrderItemId || saving) return; setSaving(true); setMessage(""); const form = new FormData(event.currentTarget); const response = await fetch("/api/reviews", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ orderItemId: data.eligibleOrderItemId, rating: Number(form.get("rating")), comment: String(form.get("comment") ?? "") }) }); const result = await response.json().catch(()=>({})) as { error?: string }; setSaving(false); if (!response.ok) return setMessage(result.error ?? "Yorum gönderilemedi."); setData({ ...data, eligibleOrderItemId: null, alreadyReviewed: true }); setMessage("Yorumunuz incelemeye gönderildi."); event.currentTarget.reset(); }
  return <section className="border-t bg-white"><div className="mx-auto max-w-7xl px-5 py-12"><h2 className="text-2xl font-black">Ürün değerlendirmeleri</h2><p className="mt-2 text-sm text-slate-600">{reviewCount ? `${rating.toFixed(1)} / 5 · ${reviewCount} onaylı değerlendirme` : "Henüz onaylı değerlendirme yok."}</p>{data?.reviews.map((review)=><article key={review.id} className="mt-4 rounded-2xl border p-5"><div className="flex justify-between"><b>{review.user.name || "BalıkGo müşterisi"}</b><span>{review.rating}/5</span></div><p className="mt-3 text-slate-700">{review.comment}</p><time className="mt-2 block text-xs text-slate-400">{new Date(review.createdAt).toLocaleDateString("tr-TR")}</time></article>)}{data && !data.reviews.length && <p className="mt-5 text-slate-500">Gösterilecek yorum bulunmuyor.</p>}{data?.eligibleOrderItemId && <form onSubmit={submit} className="mt-8 max-w-xl rounded-2xl bg-slate-50 p-5"><h3 className="font-black">Ürünü Değerlendir</h3><label className="mt-4 block text-sm font-bold">Puan<select name="rating" required defaultValue="5" className="mt-2 w-full rounded-xl border bg-white px-4 py-3">{[5,4,3,2,1].map((value)=><option key={value} value={value}>{value}</option>)}</select></label><label className="mt-4 block text-sm font-bold">Yorum<textarea name="comment" required minLength={10} maxLength={2000} rows={4} className="mt-2 w-full rounded-xl border px-4 py-3"/></label><button disabled={saving} className="mt-4 rounded-xl bg-sky-600 px-5 py-3 font-bold text-white disabled:opacity-50">{saving?"Gönderiliyor...":"İncelemeye Gönder"}</button></form>}{data?.alreadyReviewed && !data.eligibleOrderItemId && <p className="mt-6 rounded-xl bg-sky-50 p-4 text-sm text-sky-800">Bu ürün için değerlendirmeniz alınmış.</p>}{message && <p role="status" className="mt-4 rounded-xl bg-slate-100 p-4 text-sm font-bold">{message}</p>}</div></section>;
}
