import { AdminShell } from "@/app/components/admin-shell";
import { requireAdmin } from "@/app/lib/admin-auth";
import { prisma } from "@/app/lib/prisma";
import type { ProductModerationStatus } from "@prisma/client";

const SIZE = 20;
export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireAdmin(); const params = await searchParams; const value = (key: string) => typeof params[key] === "string" ? params[key] as string : "";
  const q = value("q").trim().slice(0, 120), raw = value("status"), status = ["PENDING", "APPROVED", "REJECTED", "SUSPENDED"].includes(raw) ? raw as ProductModerationStatus : undefined, page = Math.max(1, Math.min(10000, parseInt(value("page")) || 1));
  const where = { ...(status ? { moderationStatus: status } : {}), ...(q ? { OR: [{ name: { contains: q, mode: "insensitive" as const } }, { barcode: { contains: q } }, { brand: { contains: q, mode: "insensitive" as const } }, { offers: { some: { OR: [{ sellerSku: { contains: q, mode: "insensitive" as const } }, { seller: { storeName: { contains: q, mode: "insensitive" as const } } }] } } }] } : {}) };
  const [total, rows] = await Promise.all([prisma.catalogProduct.count({ where }), prisma.catalogProduct.findMany({ where, select: { id: true, name: true, category: true, brand: true, active: true, moderationStatus: true, offers: { select: { stock: true, active: true, seller: { select: { storeName: true } } } } }, orderBy: { createdAt: "desc" }, skip: (page - 1) * SIZE, take: SIZE })]);
  return <AdminShell title="Katalog ve Satıcı Teklifleri"><form className="flex gap-2"><input name="q" defaultValue={q} placeholder="Ürün, barcode, SKU veya mağaza" className="flex-1 rounded-xl border p-3"/><select name="status" defaultValue={status ?? ""} className="rounded-xl border p-3"><option value="">Tümü</option>{["PENDING", "APPROVED", "REJECTED", "SUSPENDED"].map((entry) => <option key={entry}>{entry}</option>)}</select><button className="rounded-xl bg-slate-950 px-5 text-white">Ara</button></form><div className="mt-5 overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead><tr><th className="p-4">Katalog ürünü</th><th>Kategori / Marka</th><th>Teklif</th><th>Aktif satıcı</th><th>Stokta teklif</th><th>Moderasyon</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-t"><td className="p-4 font-bold">{row.name}</td><td>{row.category}<br/>{row.brand}</td><td>{row.offers.length}</td><td>{new Set(row.offers.filter((offer) => offer.active).map((offer) => offer.seller.storeName)).size}</td><td>{row.offers.filter((offer) => offer.active && offer.stock > 0).length}</td><td>{row.moderationStatus}</td></tr>)}</tbody></table></div><p className="mt-4 text-sm">Toplam {total} · Sayfa {page}/{Math.max(1, Math.ceil(total / SIZE))}</p></AdminShell>;
}
