import Link from "next/link";
import { SellerPanelShell } from "../components/seller-panel-shell";
import { requireApprovedSeller } from "@/app/lib/seller-auth";
import { prisma } from "@/app/lib/prisma";
import { formatPrice } from "@/app/lib/products";

export default async function SellerDashboard() {
  const seller = await requireApprovedSeller();
  const today = new Date(); today.setHours(0, 0, 0, 0);
  const month = new Date(today.getFullYear(), today.getMonth(), 1);
  const [total, active, outOfStock, statusCounts, todaySales, monthSales, recent] = await Promise.all([
    prisma.product.count({ where: { sellerId: seller.id } }), prisma.product.count({ where: { sellerId: seller.id, active: true } }), prisma.sellerOffer.count({ where: { sellerId: seller.id, stock: 0, active: true } }),
    prisma.orderItem.groupBy({ by: ["status"], where: { sellerId: seller.id }, _count: { _all: true } }),
    prisma.orderItem.aggregate({ where: { sellerId: seller.id, createdAt: { gte: today }, status: { not: "CANCELLED" } }, _sum: { sellerNetAmount: true, unitPrice: true } }),
    prisma.orderItem.aggregate({ where: { sellerId: seller.id, createdAt: { gte: month }, status: { not: "CANCELLED" } }, _sum: { sellerNetAmount: true, unitPrice: true } }),
    prisma.orderItem.findMany({ where: { sellerId: seller.id }, take: 5, orderBy: { createdAt: "desc" }, include: { order: { select: { orderNumber: true } } } }),
  ]);
  const count = (status: string) => statusCounts.find((row) => row.status === status)?._count._all ?? 0;
  const money = (value: unknown) => formatPrice(Number(value ?? 0));
  const stats = [["Yeni siparişler", count("NEW"), "bg-sky-100 text-sky-700"], ["Hazırlanan", count("PREPARING"), "bg-indigo-100 text-indigo-700"], ["Kargoya hazır", count("READY_TO_SHIP"), "bg-amber-100 text-amber-800"], ["Kargoda", count("SHIPPED"), "bg-violet-100 text-violet-700"], ["Aktif ürün", active, "bg-emerald-100 text-emerald-700"], ["Stok uyarısı", outOfStock, "bg-red-100 text-red-700"]] as const;
  return <SellerPanelShell title="Genel Bakış" description="Mağazanızın gerçek zamanlı sipariş ve ürün operasyonlarını takip edin." storeName={seller.storeName}><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{stats.map(([label, value, tone]) => <Link key={label} href={label.includes("ürün") || label.includes("Stok") ? "/satici-panel/urunler" : "/satici-panel/siparisler"} className="rounded-2xl border bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><span className={`flex h-10 w-10 items-center justify-center rounded-xl ${tone}`}>●</span><p className="mt-4 text-sm font-bold text-slate-500">{label}</p><p className="mt-1 text-3xl font-black">{value}</p></Link>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-500">Bugünkü satış</p><p className="mt-2 text-3xl font-black">{money(todaySales._sum.sellerNetAmount ?? todaySales._sum.unitPrice)}</p><p className="mt-2 text-xs text-slate-500">İptal olmayan, mağazanıza ait sipariş kalemlerinden hesaplanır.</p></section><section className="rounded-2xl border bg-white p-5 shadow-sm"><p className="text-sm font-bold text-slate-500">Bu ay satış</p><p className="mt-2 text-3xl font-black">{money(monthSales._sum.sellerNetAmount ?? monthSales._sum.unitPrice)}</p><p className="mt-2 text-xs text-slate-500">Ödeme transferi değildir; satış özeti olarak gösterilir.</p></section></div><section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-black">Son siparişler</h2><Link href="/satici-panel/siparisler" className="text-sm font-black text-sky-600">Tümünü gör</Link></div>{recent.length ? <div className="mt-4 divide-y">{recent.map((item) => <div key={item.id} className="flex items-center justify-between gap-4 py-3 text-sm"><span className="min-w-0"><b>{item.order.orderNumber}</b><span className="block truncate text-slate-500">{item.productName} · {item.quantity} adet</span></span><span className="font-black">{formatPrice(Number(item.unitPrice) * item.quantity)}</span></div>)}</div> : <p className="mt-4 text-sm text-slate-500">Henüz mağazanıza ait sipariş bulunmuyor.</p>}</section><p className="mt-5 text-sm text-slate-500">Toplam ürün: <b>{total}</b> · Mağaza: <b>{seller.storeName}</b></p></SellerPanelShell>;
}
