import { notFound } from "next/navigation";
import { AdminShell } from "@/app/components/admin-shell";
import { requireAdmin } from "@/app/lib/admin-auth";
import { prisma } from "@/app/lib/prisma";
import { formatPrice } from "@/app/lib/products";

export default async function Page({ params }: { params: Promise<{ id: string }> }) {
  await requireAdmin(); const { id } = await params;
  const order = await prisma.order.findUnique({ where: { id }, select: { orderNumber: true, createdAt: true, totalAmount: true, subtotalAmount: true, discountAmount: true, status: true, couponCode: true, user: { select: { name: true, surname: true } }, payment: { select: { status: true } }, items: { select: { id: true, productName: true, productSku: true, quantity: true, unitPrice: true, status: true, shippingCompany: true, trackingNumber: true, seller: { select: { storeName: true } }, statusHistory: { select: { fromStatus: true, toStatus: true, createdAt: true }, orderBy: { createdAt: "asc" } }, refunds: { select: { status: true, amount: true } }, payout: { select: { status: true, grossAmount: true, commissionAmount: true, netAmount: true } } } } } });
  if (!order) notFound();
  return <AdminShell title={`Sipariş ${order.orderNumber}`}><div className="grid gap-4 rounded-2xl border bg-white p-5 sm:grid-cols-3"><p><b>Müşteri</b><br/>{order.user.name} {order.user.surname}</p><p><b>Tarih</b><br/>{order.createdAt.toLocaleString("tr-TR")}</p><p><b>Durum / Ödeme</b><br/>{order.status} · {order.payment?.status ?? "YOK"}</p><p><b>Ara toplam</b><br/>{formatPrice(Number(order.subtotalAmount ?? order.totalAmount))}</p><p><b>İndirim</b><br/>{formatPrice(Number(order.discountAmount))} {order.couponCode && `(${order.couponCode})`}</p><p><b>Genel toplam</b><br/>{formatPrice(Number(order.totalAmount))}</p></div><div className="mt-5 space-y-4">{order.items.map((item)=><article key={item.id} className="rounded-2xl border bg-white p-5"><h2 className="font-black">{item.seller.storeName}</h2><p className="mt-2">{item.productName} {item.productSku && `· ${item.productSku}`} · {item.quantity} adet · {formatPrice(Number(item.unitPrice))}</p><p className="mt-2 text-sm">Durum: {item.status} · Kargo: {item.shippingCompany ?? "—"} · Takip: {item.trackingNumber ?? "—"}</p>{item.refunds.map((refund, index)=><p key={index} className="mt-2 text-sm">İade: {refund.status} · {formatPrice(Number(refund.amount))}</p>)}{item.payout && <p className="mt-2 text-sm">Hakediş: {item.payout.status} · Brüt {formatPrice(Number(item.payout.grossAmount))} · Komisyon {formatPrice(Number(item.payout.commissionAmount))} · Net {formatPrice(Number(item.payout.netAmount))}</p>}<ol className="mt-3 text-xs text-slate-500">{item.statusHistory.map((history, index)=><li key={index}>{history.createdAt.toLocaleString("tr-TR")}: {history.fromStatus} → {history.toStatus}</li>)}</ol></article>)}</div></AdminShell>;
}
