import { SellerPanelShell } from "@/app/components/seller-panel-shell";
import { requireApprovedSeller } from "@/app/lib/seller-auth";
import { prisma } from "@/app/lib/prisma";

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const seller = await requireApprovedSeller(); const query = await searchParams; const page = Math.max(1, Number(query.page) || 1); const search = String(query.q ?? "").trim().slice(0, 100); const rating = Math.min(5, Math.max(0, Number(query.rating) || 0)); const status = typeof query.status === "string" && ["PENDING", "APPROVED", "REJECTED"].includes(query.status) ? query.status : "";
  const where = { product: { sellerId: seller.id, ...(search ? { OR: [{ name: { contains: search, mode: "insensitive" as const } }, { sku: { contains: search, mode: "insensitive" as const } }] } : {}) }, ...(rating ? { rating } : {}), ...(status ? { status: status as "PENDING" | "APPROVED" | "REJECTED" } : {}) };
  const reviews = await prisma.review.findMany({ where, select: { id: true, rating: true, comment: true, status: true, createdAt: true, user: { select: { name: true } }, product: { select: { name: true, sku: true } } }, orderBy: { createdAt: "desc" }, skip: (page - 1) * 20, take: 20 });
  return <SellerPanelShell title="Ürün Yorumları" description="Mağazanızdaki ürünlere gelen yorumları salt okunur görüntüleyin." storeName={seller.storeName}><form className="mb-5 flex flex-wrap gap-2"><input name="q" defaultValue={search} maxLength={100} placeholder="Ürün adı veya SKU" className="rounded-xl border px-4 py-3"/><select name="rating" defaultValue={rating || ""} className="rounded-xl border bg-white px-4"><option value="">Tüm puanlar</option>{[5,4,3,2,1].map((value)=><option key={value}>{value}</option>)}</select><select name="status" defaultValue={status} className="rounded-xl border bg-white px-4"><option value="">Tüm durumlar</option><option>PENDING</option><option>APPROVED</option><option>REJECTED</option></select><button className="rounded-xl bg-slate-950 px-5 text-white">Filtrele</button></form><div className="space-y-3">{reviews.map((review)=><article key={review.id} className="rounded-2xl border bg-white p-5"><div className="flex justify-between gap-3"><p className="font-black">{review.product.name} {review.product.sku && `· ${review.product.sku}`}</p><span>{review.rating}/5 · {review.status}</span></div><p className="mt-2 text-sm text-slate-500">{review.user.name} · {review.createdAt.toLocaleDateString("tr-TR")}</p><p className="mt-3">{review.comment}</p></article>)}</div></SellerPanelShell>;
}
