import Link from "next/link";
import { redirect } from "next/navigation";
import { auth } from "@/auth";
import { prisma } from "@/app/lib/prisma";
import { AccountHeader } from "@/app/components/account-header";
import { formatPrice } from "@/app/lib/products";
import { ORDER_STATUS_LABELS, orderStatusTone } from "@/app/lib/order-status";
const PAGE_SIZE = 20;
export default async function OrdersPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  const session = await auth(); if (!session?.user?.id) redirect("/giris"); const query = await searchParams; const requested = Number.parseInt(query.page ?? "1", 10); const page = Number.isFinite(requested) && requested > 0 ? requested : 1; const where = { userId: session.user.id };
  const [total, orders] = await prisma.$transaction([prisma.order.count({ where }), prisma.order.findMany({ where, select: { id: true, orderNumber: true, status: true, totalAmount: true, createdAt: true, shipments: { select: { status: true } }, items: { select: { productName: true, seller: { select: { storeName: true } } } } }, orderBy: { createdAt: "desc" }, skip: (page - 1) * PAGE_SIZE, take: PAGE_SIZE })]); const pages = Math.max(1, Math.ceil(total / PAGE_SIZE));
  return <main className="min-h-screen bg-slate-50"><AccountHeader /><section className="mx-auto max-w-5xl px-5 py-10"><p className="font-bold text-sky-600">HESABIM</p><h1 className="mt-1 text-3xl font-black">Siparişlerim</h1>{orders.length ? <><div className="mt-7 space-y-4">{orders.map((order) => <Link key={order.id} href={`/hesabim/siparisler/${order.id}`} className="block rounded-2xl border bg-white p-5 shadow-sm hover:border-sky-300"><div className="flex flex-wrap justify-between gap-3"><b>{order.orderNumber}</b><span className={`rounded-full px-3 py-1 text-xs font-bold ring-1 ${orderStatusTone(order.status)}`}>{ORDER_STATUS_LABELS[order.status]}</span></div><p className="mt-2 text-sm text-slate-500">{new Intl.DateTimeFormat("tr-TR", { dateStyle: "medium" }).format(order.createdAt)} · {order.items.map((item) => `${item.productName} (${item.seller.storeName})`).join(", ")}</p><p className="mt-2 text-xs font-bold text-sky-700">{order.shipments.length ? `${order.shipments.length} paket · ${order.shipments.filter((shipment) => shipment.status === "DELIVERED").length}/${order.shipments.length} teslim edildi` : "Paket hazırlığı bekleniyor"}</p><p className="mt-3 font-black">{formatPrice(Number(order.totalAmount))}</p></Link>)}</div>{pages > 1 && <nav className="mt-6 flex items-center justify-center gap-3"><Link aria-disabled={page <= 1} href={`/hesabim/siparisler?page=${Math.max(1, page - 1)}`} className={`rounded-xl border bg-white px-4 py-2 text-sm font-bold ${page <= 1 ? "pointer-events-none opacity-40" : ""}`}>Önceki</Link><span className="text-sm text-slate-600">{page} / {pages}</span><Link aria-disabled={page >= pages} href={`/hesabim/siparisler?page=${Math.min(pages, page + 1)}`} className={`rounded-xl border bg-white px-4 py-2 text-sm font-bold ${page >= pages ? "pointer-events-none opacity-40" : ""}`}>Sonraki</Link></nav>}</> : <div className="mt-7 rounded-2xl border bg-white p-10 text-center text-slate-500">Henüz siparişiniz yok. <Link href="/" className="font-bold text-sky-600">Alışverişe devam et</Link></div>}</section></main>;
}
