import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { hydrateVerifiedTestEnvironment } from "./local-test-environment";
import { createGuardedTestPrisma, TEST_DB_IDENTITY } from "./guarded-test-prisma";
import { reserveRewardForCheckout } from "../app/lib/reward-checkout";
import { consumeRewardRedemption, createPendingEarn, makeRewardAvailable } from "../app/lib/reward-ledger";
import { applyCompletedRefundRewards } from "../app/lib/reward-refund";
import { finalizeRefundExecution } from "../app/lib/refund-orchestrator";
import { RewardDomainError } from "../app/lib/reward-domain";

Object.assign(process.env, hydrateVerifiedTestEnvironment(process.env, process.cwd()));
const db = createGuardedTestPrisma(), tag = randomUUID();
const ids = { users: [] as string[], sellers: [] as string[], products: [] as string[], orders: [] as string[], policies: [] as string[] };
const now = new Date();

async function setupUser(points = 1000) { const user = await db.user.create({ data: { name: "QA", surname: "RewardRefund", email: `qa-${randomUUID()}@invalid.local`, phone: "0", passwordHash: "qa", rewardAccount: { create: { availablePoints: points } } }, include: { rewardAccount: true } }); ids.users.push(user.id); return user; }
async function order(userId: string, sellerId: string, productId: string, itemCount = 2) { const value = await db.order.create({ data: { userId, orderNumber: randomUUID(), clientRequestId: randomUUID(), subtotalAmount: 100 * itemCount, totalAmount: 100 * itemCount, recipientName: "QA", phone: "0", city: "QA", district: "QA", address: "QA reward refund address", items: { create: Array.from({ length: itemCount }, () => ({ productId, sellerId, productName: "QA", productImageUrl: "/qa", unitPrice: 100, quantity: 1, discountAmount: 0, baseUnitPrice: 100, effectiveUnitPrice: 100, finalLineAmount: 100, campaignApplied: false, campaignDiscountAmount: 0, couponApplied: false, couponDiscountAmount: 0, compositionMode: "NONE" as const, discountSource: "NONE" as const, pricingEffectiveAt: now, commissionAmount: 10, sellerNetAmount: 90, status: "DELIVERED" as const })) }, payment: { create: { amount: 100 * itemCount, provider: "TEST", providerPaymentId: randomUUID(), status: "PAID", paidAt: now } } }, include: { items: true, payment: true } }); ids.orders.push(value.id); return value; }
async function seedRedeemAndEarn(userId: string, value: Awaited<ReturnType<typeof order>>, redeemPoints = 100, earnEligibleMinor = 20_000) { const reserved = await db.$transaction(tx => reserveRewardForCheckout(tx, { userId, orderId: value.id, clientRequestId: value.clientRequestId, eligibleAmount: value.totalAmount, requestedPoints: redeemPoints, effectiveAt: now })); await db.$transaction(tx => consumeRewardRedemption(tx, { reservationId: reserved.transaction.id, userId, orderId: value.id, idempotencyKey: `qa-consume:${value.id}`, lifecycleReason: "PAYMENT_SUCCEEDED", effectiveAt: now })); const pending = await db.$transaction(tx => createPendingEarn(tx, { userId, orderId: value.id, idempotencyKey: `qa-earn:${value.id}`, effectiveAt: now, eligibleAmountMinor: earnEligibleMinor, eventAuthority: "PAYMENT_PAID_VERIFIED" })); await db.$transaction(tx => makeRewardAvailable(tx, { userId, orderId: value.id, pendingEarnId: pending.transaction.id, idempotencyKey: `qa-available:${value.id}`, effectiveAt: now })); return { reserved, pending }; }
async function refund(value: Awaited<ReturnType<typeof order>>, itemIndex: number, amount = 100) { return db.refund.create({ data: { paymentId: value.payment!.id, orderId: value.id, orderItemId: value.items[itemIndex].id, sellerId: value.items[itemIndex].sellerId, requestedByUserId: value.userId, idempotencyKey: `qa-refund:${randomUUID()}`, amount, reason: "QA authoritative refund", status: "PROCESSING", executionKey: `refund:${randomUUID()}` } }); }
const finish = (id: string) => db.$transaction(tx => finalizeRefundExecution(tx, { refundId: id, result: { outcome: "COMPLETED", providerRefundId: `provider-${id}` } }));

async function main() {
  assert.equal((await db.$queryRaw<Array<{ database: string }>>`select current_database() database`)[0].database, TEST_DB_IDENTITY.database);
  const seller = await db.user.create({ data: { name: "QA", surname: "Seller", email: `qa-seller-${tag}@invalid.local`, phone: "0", passwordHash: "qa", role: "SELLER", sellerProfile: { create: { storeName: tag, companyType: "QA", taxNumber: tag, taxOffice: "QA", city: "QA", address: "QA", description: "QA", status: "APPROVED" } } }, include: { sellerProfile: true } }); ids.users.push(seller.id); ids.sellers.push(seller.sellerProfile!.id);
  const product = await db.product.create({ data: { sellerId: seller.sellerProfile!.id, name: "QA", slug: `reward-refund-${tag}`, category: "QA", brand: "QA", price: 100, stock: 0, description: "QA", imageUrl: "/qa" } }); ids.products.push(product.id);
  const latest = await db.rewardPolicy.aggregate({ where: { policyCode: "GLOBAL" }, _max: { version: true } }); const policy = await db.rewardPolicy.create({ data: { policyCode: "GLOBAL", version: (latest._max.version ?? 0) + 1, status: "ACTIVE", earnAmountMinor: 1000, earnPoints: 10, redeemPoints: 10, redeemValueMinor: 100, expiryDays: 30, effectiveFrom: new Date(now.getTime() - 3600_000) } }); ids.policies.push(policy.id);

  const user = await setupUser(), primary = await order(user.id, seller.sellerProfile!.id, product.id); await seedRedeemAndEarn(user.id, primary);
  const economicBefore = await db.orderItem.findMany({ where: { orderId: primary.id }, select: { unitPrice: true, discountAmount: true, commissionAmount: true, sellerNetAmount: true, finalLineAmount: true } });
  const first = await refund(primary, 0), second = await refund(primary, 1);
  const duplicate = await Promise.all([finish(first.id), finish(first.id)]); assert.equal(duplicate.filter(x => !x.idempotent).length, 1);
  let txs = await db.rewardTransaction.findMany({ where: { refundId: first.id } }); assert.equal(txs.find(x => x.type === "REDEEM_RESTORED")?.points, 50); assert.equal(txs.find(x => x.type === "EARN_CLAWED_BACK")?.points, -100);
  await finish(second.id); await finish(second.id);
  txs = await db.rewardTransaction.findMany({ where: { orderId: primary.id } }); assert.equal(txs.filter(x => x.type === "REDEEM_RESTORED").reduce((sum, x) => sum + x.points, 0), 100); assert.equal(txs.filter(x => x.type === "EARN_CLAWED_BACK").reduce((sum, x) => sum + Math.abs(x.points), 0), 200);
  assert.equal((await db.rewardAccount.findUniqueOrThrow({ where: { userId: user.id } })).availablePoints, 1000); assert.deepEqual(await db.orderItem.findMany({ where: { orderId: primary.id }, select: { unitPrice: true, discountAmount: true, commissionAmount: true, sellerNetAmount: true, finalLineAmount: true } }), economicBefore);
  assert(txs.filter(x => ["REDEEM_RESTORED", "EARN_CLAWED_BACK"].includes(x.type)).every(x => x.refundId && x.refundAllocationMinor === 10000 && x.originalAllocationMinor === 20000 && x.allocationVersion === "PROPORTIONAL_CUMULATIVE_V1"));

  const raceUser = await setupUser(), raceSource = await order(raceUser.id, seller.sellerProfile!.id, product.id); await seedRedeemAndEarn(raceUser.id, raceSource); const raceRefundA = await refund(raceSource, 0), raceRefundB = await refund(raceSource, 1); const raceSpend = await order(raceUser.id, seller.sellerProfile!.id, product.id, 1);
  const raced = await Promise.all([finish(raceRefundA.id), finish(raceRefundB.id), db.$transaction(tx => reserveRewardForCheckout(tx, { userId: raceUser.id, orderId: raceSpend.id, clientRequestId: raceSpend.clientRequestId, eligibleAmount: raceSpend.totalAmount, requestedPoints: 100, effectiveAt: now }))]); assert.equal(raced.length, 3); const raceAccount = await db.rewardAccount.findUniqueOrThrow({ where: { userId: raceUser.id } }); assert.equal(raceAccount.availablePoints, 900); assert.equal(raceAccount.reservedPoints, 100); assert.equal(await db.rewardTransaction.count({ where: { orderId: raceSource.id, type: "REDEEM_RESTORED" } }), 2); assert.equal(await db.rewardTransaction.count({ where: { orderId: raceSource.id, type: "EARN_CLAWED_BACK" } }), 2);

  const earnRaceUser = await setupUser(0), earnRaceOrder = await order(earnRaceUser.id, seller.sellerProfile!.id, product.id, 1); const earnRacePending = await db.$transaction(tx => createPendingEarn(tx, { userId: earnRaceUser.id, orderId: earnRaceOrder.id, idempotencyKey: randomUUID(), effectiveAt: now, eligibleAmountMinor: 10_000, eventAuthority: "PAYMENT_PAID_VERIFIED" })); const earnRaceRefund = await refund(earnRaceOrder, 0);
  await Promise.all([finish(earnRaceRefund.id), db.$transaction(tx => makeRewardAvailable(tx, { userId: earnRaceUser.id, orderId: earnRaceOrder.id, pendingEarnId: earnRacePending.transaction.id, idempotencyKey: randomUUID(), effectiveAt: now }))]); await finish(earnRaceRefund.id); assert.equal((await db.rewardAccount.findUniqueOrThrow({ where: { userId: earnRaceUser.id } })).availablePoints, 0); assert.equal(await db.rewardTransaction.count({ where: { orderId: earnRaceOrder.id, type: "EARN_CLAWED_BACK" } }), 1);

  const stateUser = await setupUser(), stateOrder = await order(stateUser.id, seller.sellerProfile!.id, product.id, 1); await seedRedeemAndEarn(stateUser.id, stateOrder, 10, 10_000);
  const pending = await db.refund.create({ data: { paymentId: stateOrder.payment!.id, orderId: stateOrder.id, orderItemId: stateOrder.items[0].id, sellerId: seller.sellerProfile!.id, requestedByUserId: stateUser.id, idempotencyKey: randomUUID(), amount: 100, reason: "pending", status: "REQUESTED" } });
  assert.equal((await db.$transaction(tx => applyCompletedRefundRewards(tx, { refundId: pending.id }))).outcome, "not-final"); await db.refund.update({ where: { id: pending.id }, data: { status: "REJECTED" } }); assert.equal((await db.$transaction(tx => applyCompletedRefundRewards(tx, { refundId: pending.id }))).outcome, "not-final"); assert.equal(await db.rewardTransaction.count({ where: { refundId: pending.id } }), 0);

  const debtUser = await setupUser(0), debtOrder = await order(debtUser.id, seller.sellerProfile!.id, product.id, 1); const debtPending = await db.$transaction(tx => createPendingEarn(tx, { userId: debtUser.id, orderId: debtOrder.id, idempotencyKey: randomUUID(), effectiveAt: now, eligibleAmountMinor: 10_000, eventAuthority: "PAYMENT_PAID_VERIFIED" })); await db.$transaction(tx => makeRewardAvailable(tx, { userId: debtUser.id, orderId: debtOrder.id, pendingEarnId: debtPending.transaction.id, idempotencyKey: randomUUID(), effectiveAt: now })); await db.rewardAccount.update({ where: { userId: debtUser.id }, data: { availablePoints: 0 } });
  const debtRefund = await refund(debtOrder, 0); await finish(debtRefund.id); assert.equal((await db.rewardAccount.findUniqueOrThrow({ where: { userId: debtUser.id } })).availablePoints, -100);
  const impossibleOrder = await order(debtUser.id, seller.sellerProfile!.id, product.id, 1); await assert.rejects(db.$transaction(tx => reserveRewardForCheckout(tx, { userId: debtUser.id, orderId: impossibleOrder.id, clientRequestId: impossibleOrder.clientRequestId, eligibleAmount: impossibleOrder.totalAmount, requestedPoints: 10, effectiveAt: now })), error => error instanceof RewardDomainError && error.code === "REWARD_STATE_CHANGED");
  const futurePending = await db.$transaction(tx => createPendingEarn(tx, { userId: debtUser.id, orderId: impossibleOrder.id, idempotencyKey: randomUUID(), effectiveAt: now, eligibleAmountMinor: 10_000, eventAuthority: "PAYMENT_PAID_VERIFIED" })); await db.$transaction(tx => makeRewardAvailable(tx, { userId: debtUser.id, orderId: impossibleOrder.id, pendingEarnId: futurePending.transaction.id, idempotencyKey: randomUUID(), effectiveAt: now })); assert.equal((await db.rewardAccount.findUniqueOrThrow({ where: { userId: debtUser.id } })).availablePoints, 0);

  const rollbackUser = await setupUser(), rollbackOrder = await order(rollbackUser.id, seller.sellerProfile!.id, product.id, 1); await seedRedeemAndEarn(rollbackUser.id, rollbackOrder, 10, 10_000); const rollbackRefund = await refund(rollbackOrder, 0); const before = await db.rewardAccount.findUniqueOrThrow({ where: { userId: rollbackUser.id } }); await assert.rejects(db.$transaction(async tx => { await finalizeRefundExecution(tx, { refundId: rollbackRefund.id, result: { outcome: "COMPLETED", providerRefundId: randomUUID() } }); throw new Error("FORCED_ROLLBACK"); })); assert.equal((await db.refund.findUniqueOrThrow({ where: { id: rollbackRefund.id } })).status, "PROCESSING"); assert.deepEqual(await db.rewardAccount.findUniqueOrThrow({ where: { userId: rollbackUser.id } }), before); assert.equal(await db.rewardTransaction.count({ where: { refundId: rollbackRefund.id } }), 0);
  console.log("PASS: guarded TEST full/partial cumulative restoration, earn clawback debt, state boundary, replay, provenance, economic isolation and rollback");
}

async function cleanup() { const where = { orderId: { in: ids.orders } }; await db.rewardTransaction.deleteMany({ where }); await db.refund.deleteMany({ where }); await db.paymentReconciliationReview.deleteMany({ where: { payment: where } }); await db.order.deleteMany({ where: { id: { in: ids.orders } } }); await db.rewardAccount.deleteMany({ where: { userId: { in: ids.users } } }); await db.product.deleteMany({ where: { id: { in: ids.products } } }); await db.user.deleteMany({ where: { id: { in: ids.users } } }); await db.rewardPolicy.deleteMany({ where: { id: { in: ids.policies } } }); console.log("PASS: exact cleanup"); }
main().catch(error => { console.error(error); process.exitCode = 1; }).finally(async () => { try { await cleanup(); } finally { await db.$disconnect(); } });
