import assert from "node:assert/strict";
import crypto from "node:crypto";
import bcrypt from "bcryptjs";
import { hydrateVerifiedTestEnvironment } from "./local-test-environment";
import { createGuardedTestPrisma } from "./guarded-test-prisma";
import { createSellerOfferWithPriceEvidence, setSellerOfferPrice } from "../app/lib/seller-offer-price";
import { createCampaign, publishCampaign, updateCampaign, cancelCampaign } from "../app/lib/campaign";
import { addCampaignSellerOfferTarget, removeCampaignSellerOfferTarget } from "../app/lib/campaign-target";
import { createCampaignAccessCoupon } from "../app/lib/coupon-access";

const env = hydrateVerifiedTestEnvironment(process.env, process.cwd());
const db = createGuardedTestPrisma({ DATABASE_URL: env.DATABASE_URL, SUPABASE_CA_CERT_PATH: env.SUPABASE_CA_CERT_PATH });
const baseUrl = process.env.QA_BASE_URL ?? "http://localhost:3000";
const token = crypto.randomUUID(), prefix = `qa-campaign-d-${token}`;
const couponPrefix = `QAD${token.replaceAll("-", "").slice(0, 12)}`.toUpperCase();
const ids = { users: [] as string[], sellers: [] as string[], categories: [] as string[], agreements: [] as string[], catalogs: [] as string[], products: [] as string[], offers: [] as string[], campaigns: [] as string[], coupons: [] as string[] };
const address = { recipientName: "QA Customer", phone: "05000000000", city: "İstanbul", district: "Kadıköy", address: "QA campaign checkout test address", postalCode: "34000" };
const reason = "Slice D verification";

function cookieValues(response: Response) { return (typeof response.headers.getSetCookie === "function" ? response.headers.getSetCookie() : [response.headers.get("set-cookie") ?? ""]).map(value => value.split(";")[0]).filter(Boolean); }
async function login(email: string, password: string) { const csrfResponse = await fetch(`${baseUrl}/api/auth/csrf`); assert(csrfResponse.ok); const cookies = cookieValues(csrfResponse); const csrf = await csrfResponse.json() as { csrfToken: string }; const response = await fetch(`${baseUrl}/api/auth/callback/credentials`, { method: "POST", redirect: "manual", headers: { "Content-Type": "application/x-www-form-urlencoded", Cookie: cookies.join("; ") }, body: new URLSearchParams({ csrfToken: csrf.csrfToken, email, password, callbackUrl: `${baseUrl}/checkout`, json: "true" }) }); cookies.push(...cookieValues(response)); assert(response.status === 200 || response.status === 302); return cookies.join("; "); }
async function checkout(cookie: string, lines: Array<{ productId: string; sellerOfferId?: string; catalogProductId?: string; quantity?: number }>, couponCode?: string, clientRequestId = crypto.randomUUID(), extra: Record<string, unknown> = {}) { const response = await fetch(`${baseUrl}/api/orders`, { method: "POST", headers: { "Content-Type": "application/json", Cookie: cookie }, body: JSON.stringify({ clientRequestId, address, items: lines.map(line => ({ ...line, quantity: line.quantity ?? 1 })), ...(couponCode ? { couponCode } : {}), ...extra }) }); const body = await response.json() as { id?: string; orderNumber?: string; error?: string }; return { response, body, clientRequestId }; }
async function cleanup() {
  const orders = ids.users.length ? await db.order.findMany({ where: { userId: { in: ids.users } }, select: { id: true } }) : [];
  const orderIds = orders.map(x => x.id);
  if (orderIds.length) { await db.couponRedemptionAudit.deleteMany({ where: { orderId: { in: orderIds } } }); await db.couponRedemption.deleteMany({ where: { orderId: { in: orderIds } } }); await db.paymentReconciliationReview.deleteMany({ where: { payment: { orderId: { in: orderIds } } } }); await db.order.deleteMany({ where: { id: { in: orderIds } } }); }
  if (ids.campaigns.length) { await db.campaignAudit.deleteMany({ where: { campaignId: { in: ids.campaigns } } }); await db.campaignSellerOfferTarget.deleteMany({ where: { campaignId: { in: ids.campaigns } } }); }
  if (ids.offers.length) { await db.stockMovement.deleteMany({ where: { sellerOfferId: { in: ids.offers } } }); await db.sellerOfferPriceObservation.deleteMany({ where: { sellerOfferId: { in: ids.offers } } }); await db.sellerOffer.deleteMany({ where: { id: { in: ids.offers } } }); }
  if (ids.products.length) await db.product.deleteMany({ where: { id: { in: ids.products } } });
  if (ids.catalogs.length) await db.catalogProduct.deleteMany({ where: { id: { in: ids.catalogs } } });
  if (ids.coupons.length) await db.coupon.deleteMany({ where: { id: { in: ids.coupons } } });
  if (ids.campaigns.length) await db.campaign.deleteMany({ where: { id: { in: ids.campaigns } } });
  if (ids.agreements.length) await db.sellerCategoryCommissionAgreement.deleteMany({ where: { id: { in: ids.agreements } } });
  if (ids.categories.length) await db.category.deleteMany({ where: { id: { in: ids.categories } } });
  if (ids.users.length) { await db.adminAuditLog.deleteMany({ where: { actorUserId: { in: ids.users } } }); await db.user.deleteMany({ where: { id: { in: ids.users } } }); }
}

async function main() {
  const password = crypto.randomUUID(), passwordHash = await bcrypt.hash(password, 4);
  const admin = await db.user.create({ data: { name: "QA", surname: "Admin", email: `${prefix}-admin@invalid.local`, phone: "0", passwordHash, role: "ADMIN" } }); ids.users.push(admin.id);
  const customer = await db.user.create({ data: { name: "QA", surname: "Customer", email: `${prefix}-customer@invalid.local`, phone: "0", passwordHash } }); ids.users.push(customer.id);
  const category = await db.category.create({ data: { name: prefix, slug: prefix } }); ids.categories.push(category.id);
  async function makeOffer(index: number, price: string) { const user = await db.user.create({ data: { name: "QA", surname: `Seller${index}`, email: `${prefix}-seller-${index}@invalid.local`, phone: "0", passwordHash, role: "SELLER", sellerProfile: { create: { storeName: `${prefix}-${index}`, companyType: "QA", taxNumber: token.replaceAll("-", "").slice(index, index + 10), taxOffice: "QA", city: "QA", address: "QA", description: "QA", status: "APPROVED" } } }, include: { sellerProfile: true } }); ids.users.push(user.id); ids.sellers.push(user.sellerProfile!.id); const agreement = await db.sellerCategoryCommissionAgreement.create({ data: { sellerId: user.sellerProfile!.id, categoryId: category.id, commissionRate: "0.10", effectiveFrom: new Date("2020-01-01T00:00:00.000Z") } }); ids.agreements.push(agreement.id); const catalog = await db.catalogProduct.create({ data: { slug: `${prefix}-catalog-${index}`, identityKey: `${prefix}-catalog-${index}`, name: `QA ${index}`, category: "QA", categoryId: category.id, brand: "QA", description: "QA", imageUrl: "/qa", active: true, moderationStatus: "APPROVED" } }); ids.catalogs.push(catalog.id); const product = await db.product.create({ data: { sellerId: user.sellerProfile!.id, catalogProductId: catalog.id, name: `QA ${index}`, slug: `${prefix}-product-${index}`, category: "QA", categoryId: category.id, brand: "QA", price, stock: 30, description: "QA", imageUrl: "/qa", active: true, moderationStatus: "APPROVED" } }); ids.products.push(product.id); const offer = await db.$transaction(tx => createSellerOfferWithPriceEvidence(tx, { data: { sellerId: user.sellerProfile!.id, catalogProductId: catalog.id, legacyProductId: product.id, price, stock: 30, active: true }, source: "SELLER_PRODUCT_CREATE", actorUserId: user.id })); ids.offers.push(offer.id); return { user, catalog, product, offer }; }
  const a = await makeOffer(1, "1000"), b = await makeOffer(2, "500"), c = await makeOffer(3, "300"), historicalOffer = await makeOffer(4, "1000");
  const cookie = await login(customer.email, password);
  const line = (x: typeof a) => ({ productId: x.product.id, sellerOfferId: x.offer.id, catalogProductId: x.catalog.id });
  const now = Date.now(), activeWindow = { effectiveFrom: new Date(now - 3_600_000).toISOString(), effectiveUntil: new Date(now + 86_400_000).toISOString() };
  async function campaign(name: string, type: "PERCENTAGE_DISCOUNT" | "FIXED_AMOUNT_DISCOUNT" | "FIXED_PROMOTIONAL_PRICE", value: string, target: typeof a, window = activeWindow) { const rule = type === "PERCENTAGE_DISCOUNT" ? { percentage: value } : type === "FIXED_AMOUNT_DISCOUNT" ? { fixedAmount: value } : { fixedPrice: value }; const created = await createCampaign(admin.id, { internalName: `${prefix}-${name}`, campaignType: type, ...rule, ...window, reason }, db); ids.campaigns.push(created.campaign.id); await addCampaignSellerOfferTarget(admin.id, created.campaign.id, { sellerOfferId: target.offer.id, expectedVersion: 1, reason }, db); await publishCampaign(admin.id, created.campaign.id, { expectedVersion: 2, reason }, db); return created.campaign.id; }
  async function persisted(result: Awaited<ReturnType<typeof checkout>>) { assert.equal(result.response.status, 201, result.body.error); assert(result.body.id); return db.order.findUniqueOrThrow({ where: { id: result.body.id }, include: { items: { include: { payout: true } }, payment: true, couponRedemption: true } }); }
  const observationsBefore = await db.sellerOfferPriceObservation.count(), interventionsBefore = await db.adminPriceIntervention.count();
  const noCampaign = await persisted(await checkout(cookie, [line(c)])); assert.equal(noCampaign.totalAmount.toFixed(2), "300.00"); assert.equal(noCampaign.items[0].compositionMode, "NONE");
  const percentId = await campaign("percent", "PERCENTAGE_DISCOUNT", "10", a); const percent = await persisted(await checkout(cookie, [line(a)])); assert.equal(percent.totalAmount.toFixed(2), "900.00"); assert.equal(percent.items[0].campaignId, percentId); assert.equal(percent.items[0].campaignVersion, 3); assert.equal(percent.items[0].campaignDiscountAmount?.toFixed(2), "100.00");
  const accessCoupon = await createCampaignAccessCoupon(admin.id, { code: `${couponPrefix}ACCESS`, name: "QA Access", campaignId: percentId, globalRedemptionLimit: 2, perUserRedemptionLimit: 1, reason }); ids.coupons.push(accessCoupon.id);
  const accessRequest = await checkout(cookie, [line(a)], accessCoupon.code); const accessOrder = await persisted(accessRequest); assert.equal(accessOrder.totalAmount.toFixed(2), "900.00"); assert.equal(accessOrder.items[0].campaignId, percentId); assert.equal(accessOrder.items[0].couponApplied, true); assert.equal(accessOrder.items[0].couponSnapshotId, accessCoupon.id); assert.equal(accessOrder.items[0].couponReference, accessCoupon.code); assert.equal(accessOrder.items[0].couponDiscountAmount?.toFixed(2), "0.00"); assert.equal(accessOrder.couponRedemption?.state, "RESERVED");
  const accessReplay = await checkout(cookie, [line(a)], accessCoupon.code, accessRequest.clientRequestId); assert.equal(accessReplay.response.status, 200); assert.equal(accessReplay.body.id, accessOrder.id); assert.equal(await db.couponRedemption.count({ where: { couponId: accessCoupon.id } }), 1);
  await campaign("fixed", "FIXED_AMOUNT_DISCOUNT", "150", a); const fixed = await persisted(await checkout(cookie, [line(a)])); assert.equal(fixed.totalAmount.toFixed(2), "850.00");
  const promoId = await campaign("promo", "FIXED_PROMOTIONAL_PRICE", "800", a); const promo = await persisted(await checkout(cookie, [line(a)])); assert.equal(promo.totalAmount.toFixed(2), "800.00"); assert.equal(promo.items[0].campaignId, promoId);
  await campaign("future", "FIXED_PROMOTIONAL_PRICE", "100", a, { effectiveFrom: new Date(now + 3_600_000).toISOString(), effectiveUntil: new Date(now + 7_200_000).toISOString() }); const futureIgnored = await persisted(await checkout(cookie, [line(a)])); assert.equal(futureIgnored.totalAmount.toFixed(2), "800.00");
  const cancelled = await campaign("cancelled", "FIXED_PROMOTIONAL_PRICE", "100", b); await cancelCampaign(admin.id, cancelled, { expectedVersion: 3, reason }); const cancelledIgnored = await persisted(await checkout(cookie, [line(b)])); assert.equal(cancelledIgnored.totalAmount.toFixed(2), "500.00");
  const expired = await campaign("expired", "FIXED_PROMOTIONAL_PRICE", "100", b); await db.campaign.update({ where: { id: expired }, data: { effectiveFrom: new Date(now - 7_200_000), effectiveUntil: new Date(now - 3_600_000) } }); const expiredIgnored = await persisted(await checkout(cookie, [line(b)])); assert.equal(expiredIgnored.totalAmount.toFixed(2), "500.00"); assert.equal(expiredIgnored.items[0].campaignId, null);
  await campaign("non-beneficial", "FIXED_PROMOTIONAL_PRICE", "500", b); const nonBenefit = await persisted(await checkout(cookie, [line(b)])); assert.equal(nonBenefit.totalAmount.toFixed(2), "500.00");
  const couponOnlyRow = await db.coupon.create({ data: { code: `${couponPrefix}ONLY`, name: "QA", discountType: "PERCENTAGE", discountValue: "10" } }); ids.coupons.push(couponOnlyRow.id); const couponOnly = await persisted(await checkout(cookie, [line(b)], couponOnlyRow.code)); assert.equal(couponOnly.totalAmount.toFixed(2), "450.00"); assert.equal(couponOnly.items[0].compositionMode, "COUPON_ONLY"); assert.equal(couponOnly.couponRedemption?.discountAmount.toFixed(2), "50.00");
  const weakCoupon = await db.coupon.create({ data: { code: `${couponPrefix}WEAK`, name: "QA", discountType: "PERCENTAGE", discountValue: "10" } }); ids.coupons.push(weakCoupon.id); const campaignOverCoupon = await persisted(await checkout(cookie, [line(a)], weakCoupon.code)); assert.equal(campaignOverCoupon.totalAmount.toFixed(2), "800.00"); assert.equal(campaignOverCoupon.items[0].compositionMode, "CAMPAIGN_ONLY"); assert.equal(campaignOverCoupon.couponRedemption, null); assert.equal((await db.coupon.findUniqueOrThrow({ where: { id: weakCoupon.id } })).usageCount, 0);
  const strongCoupon = await db.coupon.create({ data: { code: `${couponPrefix}STRONG`, name: "QA", discountType: "PERCENTAGE", discountValue: "30" } }); ids.coupons.push(strongCoupon.id); const strongRequest = await checkout(cookie, [line(a)], strongCoupon.code); const couponOverCampaign = await persisted(strongRequest); assert.equal(couponOverCampaign.totalAmount.toFixed(2), "700.00"); assert.equal(couponOverCampaign.items[0].compositionMode, "COUPON_ONLY"); assert.equal(couponOverCampaign.items[0].campaignId, null); assert.equal(couponOverCampaign.couponRedemption?.discountAmount.toFixed(2), "300.00"); await db.coupon.update({ where: { id: strongCoupon.id }, data: { active: false, discountValue: "90" } }); const couponRetry = await checkout(cookie, [line(a)], strongCoupon.code, strongRequest.clientRequestId); assert.equal(couponRetry.response.status, 200); assert.equal(couponRetry.body.id, couponOverCampaign.id); assert.equal((await db.order.findUniqueOrThrow({ where: { id: couponOverCampaign.id } })).totalAmount.toFixed(2), "700.00");
  const equalCoupon = await db.coupon.create({ data: { code: `${couponPrefix}EQUAL`, name: "QA", discountType: "PERCENTAGE", discountValue: "20" } }); ids.coupons.push(equalCoupon.id); const equal = await persisted(await checkout(cookie, [line(a)], equalCoupon.code)); assert.equal(equal.totalAmount.toFixed(2), "800.00"); assert.equal(equal.items[0].compositionMode, "CAMPAIGN_ONLY"); assert.equal(equal.couponRedemption, null);
  await campaign("seller-b", "FIXED_AMOUNT_DISCOUNT", "100", b); const multi = await persisted(await checkout(cookie, [line(a), line(b), line(c)])); assert.equal(multi.totalAmount.toFixed(2), "1500.00"); assert.deepEqual(multi.items.map(x => x.compositionMode).sort(), ["CAMPAIGN_ONLY", "CAMPAIGN_ONLY", "NONE"]);
  const quantity = await persisted(await checkout(cookie, [{ ...line(a), quantity: 3 }])); assert.equal(quantity.totalAmount.toFixed(2), "2400.00"); assert.equal(quantity.items[0].discountAmount.toFixed(2), "600.00"); assert.equal(quantity.items[0].finalLineAmount?.toFixed(2), "2400.00");
  const badRequestId = crypto.randomUUID(), stockBeforeBad = (await db.sellerOffer.findUniqueOrThrow({ where: { id: a.offer.id } })).stock; const invalidCoupon = await persisted(await checkout(cookie, [line(a)], "DOES-NOT-EXIST", badRequestId)); assert.equal(invalidCoupon.totalAmount.toFixed(2), "800.00"); assert.equal(invalidCoupon.items[0].compositionMode, "CAMPAIGN_ONLY"); assert.equal(invalidCoupon.couponRedemption, null); assert.equal((await db.sellerOffer.findUniqueOrThrow({ where: { id: a.offer.id } })).stock, stockBeforeBad - 1);
  const spoof = await checkout(cookie, [line(a)], undefined, crypto.randomUUID(), { campaignId: promoId, effectivePrice: "1", compositionMode: "CAMPAIGN_ONLY" }); assert.equal(spoof.response.status, 400);
  await db.sellerOffer.update({ where: { id: b.offer.id }, data: { priceAnomalyHeld: true } }); const held = await checkout(cookie, [line(b)]); assert.equal(held.response.status, 409); await db.sellerOffer.update({ where: { id: b.offer.id }, data: { priceAnomalyHeld: false, stock: 0 } }); const empty = await checkout(cookie, [line(b)]); assert.equal(empty.response.status, 409); await db.sellerOffer.update({ where: { id: b.offer.id }, data: { stock: 30 } });
  const limited = await db.coupon.create({ data: { code: `${couponPrefix}LIMITED`, name: "QA", discountType: "FIXED", discountValue: "10", usageLimit: 1 } }); ids.coupons.push(limited.id); const couponRace = await Promise.all([checkout(cookie, [line(c)], limited.code), checkout(cookie, [line(c)], limited.code)]); assert.equal(couponRace.filter(x => x.response.status === 201).length, 1); assert.equal(await db.couponRedemption.count({ where: { couponId: limited.id } }), 1); assert.equal((await db.coupon.findUniqueOrThrow({ where: { id: limited.id } })).usageCount, 1);
  const duplicateId = crypto.randomUUID(), stockBeforeDuplicate = (await db.sellerOffer.findUniqueOrThrow({ where: { id: c.offer.id } })).stock; const duplicateRace = await Promise.all([checkout(cookie, [line(c)], undefined, duplicateId), checkout(cookie, [line(c)], undefined, duplicateId)]); assert.equal(await db.order.count({ where: { clientRequestId: duplicateId } }), 1); assert.equal((await db.sellerOffer.findUniqueOrThrow({ where: { id: c.offer.id } })).stock, stockBeforeDuplicate - 1); assert.equal(duplicateRace.filter(x => x.response.status === 201 || x.response.status === 200).length, 1);
  const historicalId = await campaign("historical", "PERCENTAGE_DISCOUNT", "10", historicalOffer); const retryId = crypto.randomUUID(); const historical = await persisted(await checkout(cookie, [line(historicalOffer)], undefined, retryId)); const historicalItem = historical.items[0]; assert.equal(historicalItem.finalLineAmount?.toFixed(2), "900.00"); const historicalCampaign = await db.campaign.findUniqueOrThrow({ where: { id: historicalId } }); await updateCampaign(admin.id, historicalId, { internalName: `${prefix}-historical-updated`, campaignType: "PERCENTAGE_DISCOUNT", percentage: "20", ...activeWindow, expectedVersion: historicalCampaign.version, reason }, db); await removeCampaignSellerOfferTarget(admin.id, historicalId, { sellerOfferId: historicalOffer.offer.id, expectedVersion: historicalCampaign.version + 1, reason }, db); await cancelCampaign(admin.id, historicalId, { expectedVersion: historicalCampaign.version + 2, reason }, db); await db.$transaction(tx => setSellerOfferPrice(tx, { sellerOfferId: historicalOffer.offer.id, sellerId: historicalOffer.offer.sellerId, productId: historicalOffer.product.id, expectedPriceVersion: historicalOffer.offer.priceVersion, price: "1200", source: "SELLER_PRODUCT_PATCH", actorUserId: historicalOffer.user.id })); const retry = await checkout(cookie, [line(historicalOffer)], undefined, retryId); assert.equal(retry.response.status, 200); assert.equal(retry.body.id, historical.id); const unchanged = await db.order.findUniqueOrThrow({ where: { id: historical.id }, include: { items: true, payment: true } }); assert.equal(unchanged.items[0].finalLineAmount?.toFixed(2), "900.00"); assert.equal(unchanged.items[0].campaignVersion, 3); assert.equal(unchanged.payment?.amount.toFixed(2), "900.00");
  assert.equal(await db.sellerOfferPriceObservation.count(), observationsBefore + 1); assert.equal(await db.adminPriceIntervention.count(), interventionsBefore);
  for (const order of [percent, fixed, promo, couponOnly, campaignOverCoupon, couponOverCampaign, equal, multi, quantity, invalidCoupon, historical]) { assert.equal(order.payment?.amount.toFixed(2), order.totalAmount.toFixed(2)); for (const item of order.items) { const final = item.unitPrice.mul(item.quantity).minus(item.discountAmount).toDecimalPlaces(2); assert.equal(item.finalLineAmount?.toFixed(2), final.toFixed(2)); assert.equal(item.payout?.grossAmount.toFixed(2), final.toFixed(2)); } }
  console.log("PASS: Slice D real checkout campaign/coupon composition, provenance, payment/commission/payout/stock, retry and historical economics");
}

cleanup().then(main).finally(async () => { await cleanup(); assert.equal(await db.user.count({ where: { id: { in: ids.users } } }), 0); console.log("PASS: cleanup"); await db.$disconnect(); });
