import assert from "node:assert/strict";
import crypto from "node:crypto";
import { hydrateVerifiedTestEnvironment } from "./local-test-environment";
import { createGuardedTestPrisma } from "./guarded-test-prisma";
import { createSellerOfferWithPriceEvidence } from "../app/lib/seller-offer-price";
import { createCampaign, publishCampaign, updateCampaign } from "../app/lib/campaign";
import { resolveSellerOfferCampaign } from "../app/lib/campaign-resolution";
import { CampaignParticipationError, cancelOwnCampaignParticipation, decideCampaignParticipation, listAdminCampaignParticipations, listOwnCampaignParticipations, revokeCampaignParticipation, submitCampaignParticipation } from "../app/lib/campaign-participation";

const env = hydrateVerifiedTestEnvironment(process.env, process.cwd());
const db = createGuardedTestPrisma({ DATABASE_URL: env.DATABASE_URL, SUPABASE_CA_CERT_PATH: env.SUPABASE_CA_CERT_PATH });
const token = crypto.randomUUID(), prefix = `qa-campaign-e-${token}`;
const ids = { users: [] as string[], sellers: [] as string[], catalogs: [] as string[], products: [] as string[], offers: [] as string[], campaigns: [] as string[], participations: [] as string[] };
const reason = "Slice E verification", now = new Date(), from = new Date(now.getTime() - 3600000), until = new Date(now.getTime() + 86400000);
const has = (code: string) => (error: unknown) => error instanceof CampaignParticipationError && error.code === code;
async function cleanup() { if (ids.participations.length) { await db.campaignParticipationAudit.deleteMany({ where: { participationId: { in: ids.participations } } }); await db.campaignParticipation.deleteMany({ where: { id: { in: ids.participations } } }); } if (ids.campaigns.length) { await db.campaignAudit.deleteMany({ where: { campaignId: { in: ids.campaigns } } }); await db.campaignSellerOfferTarget.deleteMany({ where: { campaignId: { in: ids.campaigns } } }); await db.campaign.deleteMany({ where: { id: { in: ids.campaigns } } }); } if (ids.offers.length) { await db.sellerOfferPriceObservation.deleteMany({ where: { sellerOfferId: { in: ids.offers } } }); await db.sellerOffer.deleteMany({ where: { id: { in: ids.offers } } }); } if (ids.products.length) await db.product.deleteMany({ where: { id: { in: ids.products } } }); if (ids.catalogs.length) await db.catalogProduct.deleteMany({ where: { id: { in: ids.catalogs } } }); if (ids.users.length) await db.user.deleteMany({ where: { id: { in: ids.users } } }); }
async function cleanupInterruptedRuns() { const users = await db.user.findMany({ where: { email: { startsWith: "qa-campaign-e-", endsWith: "@invalid.local" } }, select: { id: true, sellerProfile: { select: { id: true } } } }); const userIds = users.map(x => x.id), sellerIds = users.flatMap(x => x.sellerProfile ? [x.sellerProfile.id] : []); const campaigns = await db.campaign.findMany({ where: { internalName: { startsWith: "qa-campaign-e-" } }, select: { id: true } }); const campaignIds = campaigns.map(x => x.id); const offers = await db.sellerOffer.findMany({ where: { sellerId: { in: sellerIds } }, select: { id: true, catalogProductId: true, legacyProductId: true } }); const offerIds = offers.map(x => x.id); await db.campaignParticipationAudit.deleteMany({ where: { campaignId: { in: campaignIds } } }); await db.campaignParticipation.deleteMany({ where: { campaignId: { in: campaignIds } } }); await db.campaignAudit.deleteMany({ where: { campaignId: { in: campaignIds } } }); await db.campaignSellerOfferTarget.deleteMany({ where: { campaignId: { in: campaignIds } } }); await db.campaign.deleteMany({ where: { id: { in: campaignIds } } }); await db.sellerOfferPriceObservation.deleteMany({ where: { sellerOfferId: { in: offerIds } } }); await db.sellerOffer.deleteMany({ where: { id: { in: offerIds } } }); await db.product.deleteMany({ where: { id: { in: offers.flatMap(x => x.legacyProductId ? [x.legacyProductId] : []) } } }); await db.catalogProduct.deleteMany({ where: { id: { in: offers.map(x => x.catalogProductId) } } }); await db.user.deleteMany({ where: { id: { in: userIds } } }); }
async function user(role: "ADMIN" | "SELLER" | "CUSTOMER", suffix: string) { const row = await db.user.create({ data: { name: "QA", surname: suffix, role, email: `${prefix}-${suffix}@invalid.local`, phone: "0", passwordHash: "test-only" } }); ids.users.push(row.id); return row; }
async function offer(sellerUserId: string, index: number, held = false) { let seller = await db.sellerProfile.findUnique({ where: { userId: sellerUserId } }); if (!seller) { seller = await db.sellerProfile.create({ data: { userId: sellerUserId, storeName: `${prefix}-${index}`, companyType: "QA", taxNumber: token.replaceAll("-", "").slice(index, index + 10), taxOffice: "QA", city: "QA", address: "QA", description: "QA", status: "APPROVED" } }); ids.sellers.push(seller.id); } const catalog = await db.catalogProduct.create({ data: { slug: `${prefix}-c-${index}`, identityKey: `${prefix}-c-${index}`, name: "QA", category: "QA", brand: "QA", description: "QA", imageUrl: "/qa", active: true, moderationStatus: "APPROVED" } }); ids.catalogs.push(catalog.id); const product = await db.product.create({ data: { sellerId: seller.id, catalogProductId: catalog.id, name: "QA", slug: `${prefix}-p-${index}`, category: "QA", brand: "QA", price: "100", stock: 5, description: "QA", imageUrl: "/qa", active: true, moderationStatus: "APPROVED" } }); ids.products.push(product.id); const row = await db.$transaction(tx => createSellerOfferWithPriceEvidence(tx, { data: { sellerId: seller.id, catalogProductId: catalog.id, legacyProductId: product.id, price: "100", stock: 5, active: true }, source: "SELLER_PRODUCT_CREATE", actorUserId: sellerUserId })); ids.offers.push(row.id); if (held) await db.sellerOffer.update({ where: { id: row.id }, data: { priceAnomalyHeld: true } }); return row; }
async function campaign(adminId: string, suffix: string) { const draft = await createCampaign(adminId, { internalName: `${prefix}-${suffix}`, campaignType: "PERCENTAGE_DISCOUNT", percentage: "10", effectiveFrom: from.toISOString(), effectiveUntil: until.toISOString(), reason }, db); ids.campaigns.push(draft.campaign.id); return (await publishCampaign(adminId, draft.campaign.id, { expectedVersion: 1, reason }, db)).campaign; }
async function submit(actor: string, campaignId: string, sellerOfferId: string) { const row = await submitCampaignParticipation(actor, { campaignId, sellerOfferId }, db); if (!ids.participations.includes(row.id)) ids.participations.push(row.id); return row; }

async function main() {
  const admin1 = await user("ADMIN", "admin1"), admin2 = await user("ADMIN", "admin2"), seller1 = await user("SELLER", "seller1"), seller2 = await user("SELLER", "seller2"), customer = await user("CUSTOMER", "customer");
  const own = await offer(seller1.id, 1), foreign = await offer(seller2.id, 2), held = await offer(seller1.id, 3, true); const c1 = await campaign(admin1.id, "one");
  const couponBefore = { coupons: await db.coupon.count(), redemptions: await db.couponRedemption.count() }, orderBefore = await db.order.count();
  await assert.rejects(submit(seller1.id, c1.id, foreign.id), has("OFFER_NOT_FOUND")); await assert.rejects(submitCampaignParticipation(seller1.id, { campaignId: c1.id, sellerOfferId: own.id, sellerId: "spoof", actorUserId: admin1.id }, db), has("INVALID_INPUT"));
  const requested = await submit(seller1.id, c1.id, own.id); assert.equal(requested.status, "REQUESTED"); const replay = await submit(seller1.id, c1.id, own.id); assert.equal(replay.id, requested.id); assert.equal(replay.idempotent, true); assert.equal(await db.campaignParticipation.count({ where: { activeKey: `${c1.id}:${own.id}` } }), 1);
  assert.equal((await listOwnCampaignParticipations(seller1.id, db)).length, 1); assert.equal((await listOwnCampaignParticipations(seller2.id, db)).length, 0); await assert.rejects(listOwnCampaignParticipations(customer.id, db), has("FORBIDDEN")); assert((await listAdminCampaignParticipations(admin1.id, "REQUESTED", db)).some(x => x.id === requested.id));
  await assert.rejects(cancelOwnCampaignParticipation(seller2.id, requested.id, { expectedVersion: 1 }, db), has("PARTICIPATION_NOT_FOUND")); await assert.rejects(decideCampaignParticipation(seller1.id, requested.id, { decision: "APPROVE", expectedVersion: 1, expectedCampaignVersion: c1.version }, db), has("FORBIDDEN")); await assert.rejects(decideCampaignParticipation(seller1.id, requested.id, { decision: "REJECT", expectedVersion: 1, reason }, db), has("FORBIDDEN")); await assert.rejects(decideCampaignParticipation(customer.id, requested.id, { decision: "APPROVE", expectedVersion: 1, expectedCampaignVersion: c1.version }, db), has("FORBIDDEN"));
  const cancelled = await cancelOwnCampaignParticipation(seller1.id, requested.id, { expectedVersion: 1, reason: "Seller cancelled" }, db); assert.equal(cancelled.status, "CANCELLED"); await assert.rejects(cancelOwnCampaignParticipation(seller1.id, requested.id, { expectedVersion: 1 }, db), has("TERMINAL_PARTICIPATION"));
  const approvedRequest = await submit(seller1.id, c1.id, own.id); const beforeApprovalVersion = (await db.campaign.findUniqueOrThrow({ where: { id: c1.id } })).version; await assert.rejects(decideCampaignParticipation(admin1.id, approvedRequest.id, { decision: "APPROVE", expectedVersion: 99, expectedCampaignVersion: beforeApprovalVersion }, db), has("STALE_VERSION")); const approved = await decideCampaignParticipation(admin1.id, approvedRequest.id, { decision: "APPROVE", expectedVersion: 1, expectedCampaignVersion: beforeApprovalVersion }, db); assert.equal(approved.status, "APPROVED"); assert.equal(await db.campaignSellerOfferTarget.count({ where: { campaignId: c1.id, sellerOfferId: own.id } }), 1); assert.equal((await db.campaign.findUniqueOrThrow({ where: { id: c1.id } })).version, beforeApprovalVersion + 1); assert.equal((await resolveSellerOfferCampaign(own.id, now, db))?.campaignId, c1.id);
  const approvedAudits = await db.campaignParticipationAudit.findMany({ where: { participationId: approved.id } }); assert.deepEqual(approvedAudits.map(x => x.action).sort(), ["PARTICIPATION_APPROVED", "PARTICIPATION_REQUESTED"]); assert.equal(await db.campaignAudit.count({ where: { campaignId: c1.id, sellerOfferId: own.id, action: "CAMPAIGN_TARGET_ADDED" } }), 1);
  const c2 = await campaign(admin1.id, "reject"); const rejectRequest = await submit(seller1.id, c2.id, held.id); await assert.rejects(decideCampaignParticipation(admin1.id, rejectRequest.id, { decision: "REJECT", expectedVersion: 1 }, db), has("INVALID_INPUT")); const rejected = await decideCampaignParticipation(admin1.id, rejectRequest.id, { decision: "REJECT", expectedVersion: 1, reason }, db); assert.equal(rejected.status, "REJECTED");
  const c3 = await campaign(admin1.id, "double"); const raceRequest = await submit(seller1.id, c3.id, held.id); await decideCampaignParticipation(admin1.id, raceRequest.id, { decision: "APPROVE", expectedVersion: 1, expectedCampaignVersion: c3.version }, db); await assert.rejects(decideCampaignParticipation(admin2.id, raceRequest.id, { decision: "APPROVE", expectedVersion: 1, expectedCampaignVersion: c3.version }, db), has("TERMINAL_PARTICIPATION")); assert.equal(await db.campaignSellerOfferTarget.count({ where: { campaignId: c3.id, sellerOfferId: held.id } }), 1); assert.equal(await resolveSellerOfferCampaign(held.id, now, db), null);
  const c4 = await campaign(admin1.id, "cancel-race"); const cancelRaceRequest = await submit(seller1.id, c4.id, held.id); await cancelOwnCampaignParticipation(seller1.id, cancelRaceRequest.id, { expectedVersion: 1, reason }, db); await assert.rejects(decideCampaignParticipation(admin1.id, cancelRaceRequest.id, { decision: "APPROVE", expectedVersion: 1, expectedCampaignVersion: c4.version }, db), has("TERMINAL_PARTICIPATION"));
  const currentCampaign = await db.campaign.findUniqueOrThrow({ where: { id: c1.id } }); const currentParticipation = await db.campaignParticipation.findUniqueOrThrow({ where: { id: approved.id } }); await assert.rejects(revokeCampaignParticipation(seller1.id, approved.id, { expectedVersion: currentParticipation.version, expectedCampaignVersion: currentCampaign.version, reason }, db), has("FORBIDDEN")); const revoked = await revokeCampaignParticipation(admin1.id, approved.id, { expectedVersion: currentParticipation.version, expectedCampaignVersion: currentCampaign.version, reason }, db); assert.equal(revoked.status, "REVOKED"); await assert.rejects(revokeCampaignParticipation(admin1.id, approved.id, { expectedVersion: currentParticipation.version, expectedCampaignVersion: currentCampaign.version, reason }, db), has("TERMINAL_PARTICIPATION")); assert.equal(await db.campaignSellerOfferTarget.count({ where: { campaignId: c1.id, sellerOfferId: own.id } }), 0); assert.equal(await resolveSellerOfferCampaign(own.id, now, db), null);
  const c5 = await campaign(admin1.id, "rule-race"); const ruleRaceRequest = await submit(seller1.id, c5.id, own.id); await updateCampaign(admin2.id, c5.id, { internalName: `${prefix}-updated`, campaignType: "PERCENTAGE_DISCOUNT", percentage: "12", effectiveFrom: from.toISOString(), effectiveUntil: until.toISOString(), expectedVersion: c5.version, reason }, db); await assert.rejects(decideCampaignParticipation(admin1.id, ruleRaceRequest.id, { decision: "APPROVE", expectedVersion: 1, expectedCampaignVersion: c5.version }, db), has("STALE_VERSION"));
  const c6 = await campaign(admin1.id, "approval-rollback"); const approvalRollbackRequest = await submit(seller1.id, c6.id, own.id); const failingAudit = db.$extends({ query: { campaignParticipationAudit: { async create() { throw new Error("QA_PARTICIPATION_AUDIT_FAILURE"); } } } }); await assert.rejects(decideCampaignParticipation(admin1.id, approvalRollbackRequest.id, { decision: "APPROVE", expectedVersion: 1, expectedCampaignVersion: c6.version }, failingAudit as unknown as typeof db), /QA_PARTICIPATION_AUDIT_FAILURE/); assert.equal((await db.campaignParticipation.findUniqueOrThrow({ where: { id: approvalRollbackRequest.id } })).status, "REQUESTED"); assert.equal(await db.campaignSellerOfferTarget.count({ where: { campaignId: c6.id, sellerOfferId: own.id } }), 0); assert.equal((await db.campaign.findUniqueOrThrow({ where: { id: c6.id } })).version, c6.version);
  const approvalAfterRollback = await decideCampaignParticipation(admin1.id, approvalRollbackRequest.id, { decision: "APPROVE", expectedVersion: 1, expectedCampaignVersion: c6.version }, db); const c6After = await db.campaign.findUniqueOrThrow({ where: { id: c6.id } }); await assert.rejects(revokeCampaignParticipation(admin1.id, approvalAfterRollback.id, { expectedVersion: approvalAfterRollback.version, expectedCampaignVersion: c6After.version, reason }, failingAudit as unknown as typeof db), /QA_PARTICIPATION_AUDIT_FAILURE/); assert.equal((await db.campaignParticipation.findUniqueOrThrow({ where: { id: approvalAfterRollback.id } })).status, "APPROVED"); assert.equal(await db.campaignSellerOfferTarget.count({ where: { campaignId: c6.id, sellerOfferId: own.id } }), 1); assert.equal((await db.campaign.findUniqueOrThrow({ where: { id: c6.id } })).version, c6After.version);
  assert.equal(await db.order.count(), orderBefore); assert.deepEqual({ coupons: await db.coupon.count(), redemptions: await db.couponRedemption.count() }, couponBefore);
  const auditCount = await db.campaignParticipationAudit.count({ where: { participationId: { in: ids.participations } } }); assert(auditCount >= ids.participations.length); assert.equal(await db.campaignParticipation.count({ where: { version: { lt: 1 } } }), 0);
  console.log("PASS: Slice E guarded TEST DB seller ownership/idempotency/cancel, admin stale-writer CAS decisions/revoke, single target authority, typed atomic audit/rollback, hold and coupon/order boundaries");
}
cleanupInterruptedRuns().then(cleanup).then(main).finally(async () => { await cleanup(); assert.equal(await db.campaignParticipation.count({ where: { id: { in: ids.participations } } }), 0); console.log("PASS: cleanup"); await db.$disconnect(); });
