import assert from "node:assert/strict";
import crypto from "node:crypto";
import { hash } from "bcryptjs";
import { hydrateVerifiedTestEnvironment } from "./local-test-environment";
import { createGuardedTestPrisma, TEST_DB_IDENTITY } from "./guarded-test-prisma";
import { AdminPriceOverrideError, overrideSellerOfferPriceByAdmin } from "../app/lib/admin-price-override";
import { createSellerOfferWithPriceEvidence, setSellerOfferPrice } from "../app/lib/seller-offer-price";

const env=hydrateVerifiedTestEnvironment(process.env,process.cwd());
const prisma=createGuardedTestPrisma({DATABASE_URL:env.DATABASE_URL,SUPABASE_CA_CERT_PATH:env.SUPABASE_CA_CERT_PATH});
const token=crypto.randomUUID(),prefix=`qa-admin-price-${token}`;
const ids={users:[] as string[],sellers:[] as string[],catalogs:[] as string[],products:[] as string[],offers:[] as string[],orders:[] as string[]};
const hasCode=(code:string)=>(error:unknown)=>error instanceof AdminPriceOverrideError&&error.code===code;
async function cleanup(){
  if(ids.orders.length)await prisma.order.deleteMany({where:{id:{in:ids.orders}}});
  if(ids.offers.length){await prisma.adminPriceIntervention.deleteMany({where:{sellerOfferId:{in:ids.offers}}});const holds=await prisma.sellerOfferPriceAnomalyHold.findMany({where:{sellerOfferId:{in:ids.offers}},select:{id:true}});await prisma.sellerOfferPriceAnomalyRelease.deleteMany({where:{holdId:{in:holds.map(h=>h.id)}}});await prisma.sellerOfferPriceAnomalyHold.deleteMany({where:{id:{in:holds.map(h=>h.id)}}});await prisma.sellerOfferPriceObservation.deleteMany({where:{sellerOfferId:{in:ids.offers}}});await prisma.sellerOffer.deleteMany({where:{id:{in:ids.offers}}});}
  if(ids.products.length)await prisma.product.deleteMany({where:{id:{in:ids.products}}});if(ids.catalogs.length)await prisma.catalogProduct.deleteMany({where:{id:{in:ids.catalogs}}});if(ids.users.length)await prisma.user.deleteMany({where:{id:{in:ids.users}}});
  if(ids.users.length)assert.equal(await prisma.user.count({where:{id:{in:ids.users}}}),0,"cleanup failed");
}
async function main(){
  const identity=await prisma.$queryRaw<Array<{database:string;role:string}>>`select current_database() database,current_user role`;assert.deepEqual(identity[0],{database:TEST_DB_IDENTITY.database,role:"postgres"});
  const passwordHash=await hash("qa-only",4);
  const admin1=await prisma.user.create({data:{name:"QA",surname:"Admin1",email:`${prefix}-a1@invalid.local`,phone:"0",passwordHash,role:"ADMIN"}});const admin2=await prisma.user.create({data:{name:"QA",surname:"Admin2",email:`${prefix}-a2@invalid.local`,phone:"0",passwordHash,role:"ADMIN"}});const customer=await prisma.user.create({data:{name:"QA",surname:"Customer",email:`${prefix}-c@invalid.local`,phone:"0",passwordHash}});ids.users.push(admin1.id,admin2.id,customer.id);
  for(let i=0;i<3;i+=1){const user=await prisma.user.create({data:{name:"QA",surname:String(i),email:`${prefix}-s${i}@invalid.local`,phone:"0",passwordHash,role:"SELLER",sellerProfile:{create:{storeName:`${prefix}-${i}`,companyType:"QA",taxNumber:crypto.randomUUID().replaceAll("-","").slice(0,10),taxOffice:"QA",city:"QA",address:"QA",description:"QA",status:"APPROVED"}}},include:{sellerProfile:true}});ids.users.push(user.id);ids.sellers.push(user.sellerProfile!.id);}
  const catalog=await prisma.catalogProduct.create({data:{slug:`${prefix}-catalog`,identityKey:prefix,name:"QA",category:"QA",brand:"QA",description:"QA",imageUrl:"/qa",active:true,moderationStatus:"APPROVED"}});ids.catalogs.push(catalog.id);
  async function make(i:number,price:string){const product=await prisma.product.create({data:{sellerId:ids.sellers[i],catalogProductId:catalog.id,name:"QA",slug:`${prefix}-p${i}`,category:"QA",brand:"QA",price,stock:5,description:"QA",imageUrl:"/qa",active:true,moderationStatus:"APPROVED"}});ids.products.push(product.id);const offer=await prisma.$transaction(tx=>createSellerOfferWithPriceEvidence(tx,{data:{sellerId:ids.sellers[i],catalogProductId:catalog.id,legacyProductId:product.id,sellerSku:`${prefix}-${i}`,price,stock:5},source:"SELLER_PRODUCT_CREATE",actorUserId:ids.users[3+i]}));ids.offers.push(offer.id);return{product,offer};}
  await make(0,"100");await make(1,"110");const target=await make(2,"100");
  await assert.rejects(()=>overrideSellerOfferPriceByAdmin({actorUserId:ids.users[5],sellerOfferId:target.offer.id,expectedPriceVersion:1,price:"105",reason:"seller denied"},prisma),hasCode("FORBIDDEN"));await assert.rejects(()=>overrideSellerOfferPriceByAdmin({actorUserId:customer.id,sellerOfferId:target.offer.id,expectedPriceVersion:1,price:"105",reason:"customer denied"},prisma),hasCode("FORBIDDEN"));await assert.rejects(()=>overrideSellerOfferPriceByAdmin({actorUserId:admin1.id,sellerOfferId:target.offer.id,expectedPriceVersion:1,price:"105",reason:"  "},prisma),hasCode("INVALID_REASON"));
  const normal=await overrideSellerOfferPriceByAdmin({actorUserId:admin1.id,sellerOfferId:target.offer.id,expectedPriceVersion:1,price:"105",reason:"Approved market correction"},prisma);assert.equal(normal.changed,true);assert.equal(normal.priceVersion,2);assert.equal(normal.priceAnomalyHeld,false);
  const noOp=await overrideSellerOfferPriceByAdmin({actorUserId:admin1.id,sellerOfferId:target.offer.id,expectedPriceVersion:2,price:"105.00",reason:"No economic change"},prisma);assert.equal(noOp.changed,false);assert.equal(await prisma.adminPriceIntervention.count({where:{sellerOfferId:target.offer.id}}),1);assert.equal(await prisma.sellerOfferPriceObservation.count({where:{sellerOfferId:target.offer.id}}),2);
  const order=await prisma.order.create({data:{userId:customer.id,orderNumber:`QA-ADMIN-${token}`,clientRequestId:crypto.randomUUID(),totalAmount:"105",recipientName:"QA",phone:"0",city:"QA",district:"QA",address:"QA",items:{create:{productId:target.product.id,catalogProductId:catalog.id,sellerOfferId:target.offer.id,sellerId:ids.sellers[2],productName:"QA",productImageUrl:"/qa",unitPrice:"105",quantity:1}},payment:{create:{amount:"105"}}}});ids.orders.push(order.id);
  const critical=await overrideSellerOfferPriceByAdmin({actorUserId:admin1.id,sellerOfferId:target.offer.id,expectedPriceVersion:2,price:"10",reason:"Exercise automatic anomaly hold"},prisma);assert.equal(critical.priceVersion,3);assert.equal(critical.priceAnomalyHeld,true);
  const stillCritical=await overrideSellerOfferPriceByAdmin({actorUserId:admin1.id,sellerOfferId:target.offer.id,expectedPriceVersion:3,price:"1",reason:"Unsafe correction must remain held"},prisma);assert.equal(stillCritical.priceVersion,4);assert.equal(stillCritical.priceAnomalyHeld,true);
  const safe=await overrideSellerOfferPriceByAdmin({actorUserId:admin1.id,sellerOfferId:target.offer.id,expectedPriceVersion:4,price:"100",reason:"Restore safe current listing price"},prisma);assert.equal(safe.priceVersion,5);assert.equal(safe.priceAnomalyHeld,false);
  await assert.rejects(()=>overrideSellerOfferPriceByAdmin({actorUserId:admin1.id,sellerOfferId:target.offer.id,expectedPriceVersion:4,price:"99",reason:"Stale admin mutation"},prisma),hasCode("STALE_PRICE_VERSION"));
  const adminRace=await Promise.allSettled([admin1.id,admin2.id].map((actorUserId,index)=>overrideSellerOfferPriceByAdmin({actorUserId,sellerOfferId:target.offer.id,expectedPriceVersion:5,price:String(101+index),reason:"Concurrent admin correction"},prisma)));assert.equal(adminRace.filter(x=>x.status==="fulfilled").length,1);assert.equal(adminRace.filter(x=>x.status==="rejected").length,1);
  const current=await prisma.sellerOffer.findUniqueOrThrow({where:{id:target.offer.id}});const sellerAdminRace=await Promise.allSettled([prisma.$transaction(tx=>setSellerOfferPrice(tx,{sellerOfferId:current.id,sellerId:current.sellerId,productId:target.product.id,expectedPriceVersion:current.priceVersion,price:"103",source:"SELLER_PRODUCT_PATCH",actorUserId:ids.users[5]})),overrideSellerOfferPriceByAdmin({actorUserId:admin1.id,sellerOfferId:current.id,expectedPriceVersion:current.priceVersion,price:"104",reason:"Concurrent seller admin correction"},prisma)]);assert.equal(sellerAdminRace.filter(x=>x.status==="fulfilled").length,1);assert.equal(sellerAdminRace.filter(x=>x.status==="rejected").length,1);
  const observations=await prisma.sellerOfferPriceObservation.findMany({where:{sellerOfferId:target.offer.id,source:"ADMIN_PRICE_OVERRIDE"}});assert(observations.length>=4&&observations.every(x=>x.actorUserId===admin1.id||x.actorUserId===admin2.id));const audits=await prisma.adminPriceIntervention.findMany({where:{sellerOfferId:target.offer.id}});assert(audits.every(x=>x.actorRole==="ADMIN"&&x.reason.length>=3));assert(audits.some(x=>x.previousHoldState&&!x.resultingHoldState));assert(audits.some(x=>x.resultingHoldState));
  const historical=await prisma.order.findUniqueOrThrow({where:{id:order.id},include:{items:true,payment:true}});assert.equal(historical.items[0].unitPrice.toString(),"105");assert.equal(historical.payment!.amount.toString(),"105");
  console.log("PASS: #25 Slice F guarded TEST DB role denial, reason, ADMIN observation/audit, CAS, concurrency, hold/release safety, no-op and historical economics");
}
cleanup().then(main).finally(async()=>{await cleanup();await prisma.$disconnect();});
