import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
import { migrationChildEnvironment, selectMigrationTarget, validateOperationTarget } from "./guarded-operation-prisma.ts";
import { repositoryRoot, resolveLocalPrismaCli, runLocalPrisma, sanitizeChildText, validatePrismaEntrypoint } from "./local-prisma-runner.ts";

const uri = (ref: string) => `postgresql://postgres.${ref}:password@aws-0-eu-west-1.pooler.supabase.com:5432/postgres`;
assert.throws(() => validateOperationTarget({ DIRECT_URL: uri("lkvzkscoworbudceknbo"), DB_TARGET_PROJECT_REF: "lkvzkscoworbudceknbo" }, "write"), /EXPLICIT_CONFIRMATION/);
assert.doesNotThrow(() => validateOperationTarget({ DIRECT_URL: uri("lkvzkscoworbudceknbo"), DB_TARGET_PROJECT_REF: "lkvzkscoworbudceknbo" }, "read"));
assert.throws(() => validateOperationTarget({ DIRECT_URL: uri("other"), DB_TARGET_PROJECT_REF: "expected" }, "read"), /MISMATCH/);
assert.throws(() => validateOperationTarget({ DIRECT_URL: uri("other") }, "read"), /REQUIRED/);
const testUri = "postgresql://postgres.ikfalxycwusprjnhnxzf:password@aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres";
const otherUri = uri("other");
const testEnv = { DATABASE_URL: testUri, DIRECT_URL: otherUri, DB_TARGET_PROJECT_REF: "ikfalxycwusprjnhnxzf", SUPABASE_CA_CERT_PATH: "local-ca.pem" };
const selected = selectMigrationTarget(testEnv, "test");
assert.equal(selected.connectionString, testUri);
const child = migrationChildEnvironment(testEnv, selected);
assert.equal(child.DATABASE_URL, testUri);
assert.equal(child.DIRECT_URL, testUri);
assert.notEqual(child.DIRECT_URL, otherUri);
assert.throws(() => selectMigrationTarget({ ...testEnv, DATABASE_URL: otherUri }, "test"), /REFUSING_NON_TEST_DATABASE/);
assert.throws(() => selectMigrationTarget({ ...testEnv, DB_TARGET_PROJECT_REF: "other" }, "test"), /MISMATCH/);
assert.throws(() => selectMigrationTarget({ ...testEnv, DB_TARGET_PROJECT_REF: undefined }, "test"), /MISMATCH/);
assert.throws(() => selectMigrationTarget(testEnv, undefined), /MIGRATION_MODE_REQUIRED/);
assert.throws(() => selectMigrationTarget(testEnv, "staging"), /MIGRATION_MODE_REQUIRED/);
assert.throws(() => selectMigrationTarget({ ...testEnv, DATABASE_URL: `${testUri}?sslmode=no-verify` }, "test"), /INSECURE_TLS/);
assert.throws(() => selectMigrationTarget({ ...testEnv, NODE_TLS_REJECT_UNAUTHORIZED: "0" }, "test"), /INSECURE_TLS_ENVIRONMENT/);
assert.throws(() => selectMigrationTarget({ DIRECT_URL: uri("lkvzkscoworbudceknbo"), DB_TARGET_PROJECT_REF: "lkvzkscoworbudceknbo", SUPABASE_CA_CERT_PATH: "local-ca.pem" }, "production"), /EXPLICIT_CONFIRMATION/);
const production = selectMigrationTarget({ DIRECT_URL: uri("lkvzkscoworbudceknbo"), DB_TARGET_PROJECT_REF: "lkvzkscoworbudceknbo", SUPABASE_CA_CERT_PATH: "local-ca.pem", ALLOW_PRODUCTION_DB_OPERATION: "I_ACKNOWLEDGE_BALIKGO_PRODUCTION_WRITE" }, "production");
assert.equal(production.actualRef, "lkvzkscoworbudceknbo");
let safeError = "";
try { selectMigrationTarget({ ...testEnv, DATABASE_URL: otherUri }, "test"); } catch (error) { safeError = error instanceof Error ? error.message : String(error); }
assert(!safeError.includes("password") && !safeError.includes("postgresql://"));
const runnerSource = readFileSync(new URL("./run-prisma-migrate.ts", import.meta.url), "utf8");
const localRunnerSource = readFileSync(new URL("./local-prisma-runner.ts", import.meta.url), "utf8");
assert(!/npx\.cmd|cmd\.exe|powershell|shell:\s*true/i.test(runnerSource + localRunnerSource));
assert.match(runnerSource, /migrationChildEnvironment\(process\.env, selected\)/);
const root = repositoryRoot();
const cli = resolveLocalPrismaCli(root);
assert.equal(cli.version, "7.9.1");
assert.match(cli.entrypoint.replaceAll("\\", "/"), /\/node_modules\/prisma\/build\/index\.js$/);
let invocation: { executable?: string; args?: readonly string[]; options?: Record<string, unknown> } = {};
runLocalPrisma({ root, action: "status", env: child as unknown as NodeJS.ProcessEnv, spawn: ((executable: string, args: readonly string[], options: Record<string, unknown>) => { invocation = { executable, args, options }; return { pid: 1, output: [], stdout: "", stderr: "", status: 0, signal: null, error: undefined }; }) as never });
assert.equal(invocation.executable, process.execPath);
assert.deepEqual(invocation.args, [cli.entrypoint, "migrate", "status"]);
assert.equal(invocation.options?.cwd, root);
assert.equal(invocation.options?.shell, false);
assert.equal((invocation.options?.env as Record<string, string>).DATABASE_URL, testUri);
assert.equal((invocation.options?.env as Record<string, string>).DIRECT_URL, testUri);
assert.equal((invocation.options?.env as Record<string, string>).NODE_EXTRA_CA_CERTS, "local-ca.pem");
assert.throws(() => runLocalPrisma({ root, action: "unknown", env: child as unknown as NodeJS.ProcessEnv }), /MIGRATION_ACTION_REQUIRED/);
assert.throws(() => resolveLocalPrismaCli(`${root}/missing`), /ENOENT|NOT_FOUND/);
assert.throws(() => validatePrismaEntrypoint(root, root, cli.entrypoint), /ENTRYPOINT_INVALID/);
assert.throws(() => runLocalPrisma({ root, action: "status", env: child as unknown as NodeJS.ProcessEnv, spawn: (() => ({ pid: 1, output: [], stdout: "", stderr: testUri, status: 2, signal: null, error: undefined })) as never }), /PRISMA_CHILD_EXIT_2/);
assert.throws(() => runLocalPrisma({ root, action: "status", env: child as unknown as NodeJS.ProcessEnv, spawn: (() => ({ pid: 1, output: [], stdout: "", stderr: "", status: null, signal: "SIGTERM", error: undefined })) as never }), /PRISMA_CHILD_SIGNAL:SIGTERM/);
assert.throws(() => runLocalPrisma({ root, action: "status", env: child as unknown as NodeJS.ProcessEnv, spawn: (() => ({ pid: 1, output: [], stdout: "", stderr: "", status: null, signal: null, error: Object.assign(new Error(testUri), { name: "SafeSpawnError" }) })) as never }), /PRISMA_CHILD_SPAWN_FAILED:SafeSpawnError/);
assert.equal(sanitizeChildText(`failed ${testUri}`, [testUri]), "failed [REDACTED]");
const prismaConfig = readFileSync(new URL("../prisma.config.ts", import.meta.url), "utf8");
assert.match(prismaConfig, /env\("DIRECT_URL"\)/);
console.log("PASS: operation and migration target guards pin TEST Prisma child URLs and preserve production confirmation.");
