import { strict as assert } from "node:assert";
import { readFileSync } from "node:fs";
const service = readFileSync(new URL("../app/lib/stock-truth.ts", import.meta.url), "utf8");
const orders = readFileSync(new URL("../app/api/orders/route.ts", import.meta.url), "utf8");
const cancellation = readFileSync(new URL("../app/lib/order-orchestrator.ts", import.meta.url), "utf8");
const inventory = readFileSync(new URL("../app/api/seller/products/[id]/inventory/route.ts", import.meta.url), "utf8");
const productPatch = readFileSync(new URL("../app/api/seller/products/[id]/route.ts", import.meta.url), "utf8");
assert.match(orders, /stock:v1:checkout:\$\{clientRequestId\}:\$\{product\.sellerOffer\.id\}/);
assert.match(orders, /decrementForCheckout\(tx,/);
assert.match(orders, /actorSellerId: product\.sellerId/);
assert.match(orders, /error\.code === "INSUFFICIENT_STOCK"/);
assert.match(cancellation, /stock:v1:cancellation:\$\{item\.id\}/);
assert.match(inventory + productPatch, /expectedInventoryVersion/);
assert.match(service, /pg_advisory_xact_lock/);
assert.match(service, /IDEMPOTENCY_CONFLICT/);
assert.match(service, /quantity <= 0\) throw new StockTruthError\("INVALID_QUANTITY"\)/);
assert.match(service, /quantity < 0 \|\| !Number\.isInteger\(input\.expectedVersion\) \|\| input\.expectedVersion < 0\) throw new StockTruthError\("INVALID_QUANTITY"\)/);
for (const code of ["INSUFFICIENT_STOCK", "STALE_INVENTORY_VERSION", "IDEMPOTENCY_CONFLICT", "OFFER_NOT_FOUND", "OWNERSHIP_MISMATCH", "INVALID_QUANTITY"]) assert(service.includes(`\"${code}\"`));
assert.match(service, /inventoryVersion"="inventoryVersion"\+1/);
assert(!/stockMovement\.(update|updateMany|delete|deleteMany|upsert)/.test(readFileSync(new URL("../app/lib/stock-truth.ts", import.meta.url), "utf8")));
for (const source of [orders, cancellation, inventory, productPatch]) assert(!/sellerOffer\.(update|updateMany)[\s\S]{0,160}stock\s*:/.test(source));
console.log("PASS: Stock Truth static invariants, domain validation, centralized mutations and append-only production usage verified.");
