import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { evaluateFeature, FEATURE_FLAG_KEYS, getFeatureSafetySnapshot, loadFeatureSafetyConfig, parseFeatureSafetyConfig, rolloutBucket } from "../app/lib/feature-flags-core";
import { toCustomerOrderDto } from "../app/lib/customer-shipment-dto";
import type { CustomerOrderRecord } from "../app/lib/customer-order-select";

const json = (flags: unknown[], globalKillSwitch = false) => JSON.stringify({ version: "qa-v1", globalKillSwitch, flags });
const flag = (overrides: Record<string, unknown> = {}) => ({ key: "CUSTOMER_SHIPMENT_TIMELINE", enabled: true, rolloutPercentage: 100, allowlist: [], killSwitch: false, ...overrides });
const at = new Date("2026-08-20T00:00:00Z");
const defaults = loadFeatureSafetyConfig(undefined);
assert.equal(evaluateFeature(defaults, "CUSTOMER_SHIPMENT_TIMELINE", {}, at).enabled, true, "enabled default failed");
assert.equal(evaluateFeature(parseFeatureSafetyConfig(json([flag({ enabled: false })])), "CUSTOMER_SHIPMENT_TIMELINE", {}, at).enabled, false, "disabled state failed");
assert.equal(evaluateFeature(parseFeatureSafetyConfig(json([flag()], true)), "CUSTOMER_SHIPMENT_TIMELINE", { userId: "u" }, at).reason, "GLOBAL_KILL_SWITCH");
assert.equal(evaluateFeature(parseFeatureSafetyConfig(json([flag({ killSwitch: true })])), "CUSTOMER_SHIPMENT_TIMELINE", { userId: "u" }, at).reason, "FEATURE_KILL_SWITCH");
assert.equal(evaluateFeature(parseFeatureSafetyConfig(json([flag({ rolloutPercentage: 0, allowlist: ["internal"] })])), "CUSTOMER_SHIPMENT_TIMELINE", { userId: "internal" }, at).reason, "ALLOWLIST");
assert.equal(evaluateFeature(parseFeatureSafetyConfig(json([flag({ rolloutPercentage: 0 })])), "CUSTOMER_SHIPMENT_TIMELINE", { userId: "u" }, at).enabled, false);
assert.equal(evaluateFeature(parseFeatureSafetyConfig(json([flag({ rolloutPercentage: 100 })])), "CUSTOMER_SHIPMENT_TIMELINE", {}, at).enabled, true);
const quarter = parseFeatureSafetyConfig(json([flag({ rolloutPercentage: 25 })])); const first = evaluateFeature(quarter, "CUSTOMER_SHIPMENT_TIMELINE", { userId: "stable-user" }, at); const second = evaluateFeature(quarter, "CUSTOMER_SHIPMENT_TIMELINE", { userId: "stable-user" }, at);
assert.deepEqual(first, second); assert.equal(rolloutBucket("CUSTOMER_SHIPMENT_TIMELINE", "stable-user"), rolloutBucket("CUSTOMER_SHIPMENT_TIMELINE", "stable-user"));
assert.equal(evaluateFeature(quarter, "CUSTOMER_SHIPMENT_TIMELINE", {}, at).reason, "MISSING_CONTEXT");
assert.throws(() => parseFeatureSafetyConfig(json([flag({ rolloutPercentage: 101 })])), /FLAG_STATE_INVALID/);
assert.throws(() => parseFeatureSafetyConfig(json([{ ...flag(), key: "UNKNOWN" }])), /UNKNOWN_FEATURE_FLAG/);
assert.throws(() => parseFeatureSafetyConfig(json([flag(), flag()])), /DUPLICATE_FEATURE_FLAG/);
assert.throws(() => parseFeatureSafetyConfig(json([{ ...flag(), key: "PAYMENT_VERIFICATION" }])), /FORBIDDEN_CRITICAL_FLAG/);
const invalid = loadFeatureSafetyConfig("not-json"); assert.equal(invalid.valid, false); assert.equal(evaluateFeature(invalid, "CUSTOMER_SHIPMENT_TIMELINE", { userId: "u" }, at).reason, "CONFIG_INVALID");
const sensitive = parseFeatureSafetyConfig(json([flag({ allowlist: ["private-subject-id"] })])); const snapshot = getFeatureSafetySnapshot(sensitive, "test"); const serialized = JSON.stringify(snapshot);
assert.ok(!serialized.includes("private-subject-id") && !serialized.includes("allowlist")); assert.equal(new Set(FEATURE_FLAG_KEYS).size, FEATURE_FLAG_KEYS.length);
const dtoSource = readFileSync(new URL("../app/lib/customer-shipment-dto.ts", import.meta.url), "utf8"); assert.match(dtoSource, /trackingLinkEnabled \? trackingUrlFor[\s\S]*: null/); assert.match(dtoSource, /timelineEnabled \? events[\s\S]*: \[\]/);
const eventTime = new Date("2026-08-20T12:00:00Z"); const order = { id: "order-1", userId: "user-1", orderNumber: "BG-1", status: "SHIPPED", totalAmount: 10, subtotalAmount: 10, discountAmount: 0, couponCode: null, recipientName: "QA", phone: "0", city: "QA", district: "QA", address: "QA", postalCode: null, createdAt: eventTime, updatedAt: eventTime, payment: { status: "PAID" }, items: [], shipments: [{ id: "shipment-1", status: "SHIPPED", carrierCode: "YURTICI", carrierName: "Yurtiçi Kargo", trackingNumber: "ABC123", preparedAt: null, shippedAt: eventTime, deliveredAt: null, estimatedDeliveryAt: null, seller: { id: "seller-1", storeName: "Store", storeSlug: "store" }, items: [], events: [{ id: "event-1", status: "IN_TRANSIT", eventTime, receivedAt: eventTime, location: "Hub", description: "Yolda", applied: true, source: "YURTICI", externalEventId: "internal", payloadHash: null }] }] } as unknown as CustomerOrderRecord;
const previous = process.env.BALIKGO_RELEASE_SAFETY_CONFIG;
process.env.BALIKGO_RELEASE_SAFETY_CONFIG = json([]); const enhanced = toCustomerOrderDto(order); assert.ok(enhanced.shipments[0].trackingUrl && enhanced.shipments[0].timeline.length === 1);
process.env.BALIKGO_RELEASE_SAFETY_CONFIG = json([flag({ killSwitch: true }), { ...flag({ killSwitch: true }), key: "CUSTOMER_TRACKING_LINK" }]); const degraded = toCustomerOrderDto(order); assert.equal(degraded.shipments[0].trackingUrl, null); assert.deepEqual(degraded.shipments[0].timeline, []); assert.equal(degraded.shipments[0].trackingNumber, "ABC123"); assert.equal(degraded.shipments[0].normalizedStatus, "HANDED_TO_CARRIER");
process.env.BALIKGO_RELEASE_SAFETY_CONFIG = "invalid"; const safeFallback = toCustomerOrderDto(order); assert.equal(safeFallback.shipments[0].trackingUrl, null); assert.deepEqual(safeFallback.shipments[0].timeline, []); if (previous === undefined) delete process.env.BALIKGO_RELEASE_SAFETY_CONFIG; else process.env.BALIKGO_RELEASE_SAFETY_CONFIG = previous;
console.log("PASS: feature flags, kill switches, deterministic rollout, safe fallback, forbidden critical flags, metadata redaction and graceful degradation contracts verified.");
