import "dotenv/config";
import bcrypt from "bcryptjs";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient } from "@prisma/client";

const connectionString = process.env.DIRECT_URL ?? process.env.DATABASE_URL;
const password = process.env.QA_SHIPPING_PASSWORD ?? "";
const baseUrl = process.env.QA_BASE_URL ?? "http://localhost:3000";
if (!connectionString || !password) throw new Error("QA runtime configuration is missing.");
const prisma = new PrismaClient({ adapter: new PrismaPg({ connectionString }) });
const prefix = "QA-SHIPPING-";
const emailPrefix = "qa-shipping-";
function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
function cookieValues(response: Response) { const headers = typeof response.headers.getSetCookie === "function" ? response.headers.getSetCookie() : [response.headers.get("set-cookie") ?? ""]; return headers.map((value) => value.split(";", 1)[0]).filter(Boolean); }
async function cleanup() { const users = await prisma.user.findMany({ where: { email: { startsWith: emailPrefix, endsWith: "@invalid.local" } }, select: { id: true, sellerProfile: { select: { id: true, products: { select: { catalogProductId: true } } } } } }); if (!users.length) return; const ids = users.map((user) => user.id); const sellerIds = users.flatMap((user) => user.sellerProfile ? [user.sellerProfile.id] : []); const catalogIds = [...new Set(users.flatMap((user) => user.sellerProfile?.products.map((product) => product.catalogProductId).filter((id): id is string => Boolean(id)) ?? []))]; await prisma.shipment.deleteMany({ where: { order: { userId: { in: ids } } } }); await prisma.order.deleteMany({ where: { userId: { in: ids } } }); if (sellerIds.length) await prisma.sellerOffer.deleteMany({ where: { sellerId: { in: sellerIds } } }); await prisma.user.deleteMany({ where: { id: { in: ids } } }); if (catalogIds.length) await prisma.catalogProduct.deleteMany({ where: { id: { in: catalogIds }, offers: { none: {} } } }); }
async function login(email: string) { const cookies: string[] = []; const csrfResponse = await fetch(`${baseUrl}/api/auth/csrf`); assert(csrfResponse.ok, "CSRF endpoint failed."); cookies.push(...cookieValues(csrfResponse)); const csrf = await csrfResponse.json() as { csrfToken?: string }; assert(csrf.csrfToken, "CSRF token missing."); const response = await fetch(`${baseUrl}/api/auth/callback/credentials`, { method: "POST", redirect: "manual", headers: { "Content-Type": "application/x-www-form-urlencoded", Cookie: cookies.join("; ") }, body: new URLSearchParams({ csrfToken: csrf.csrfToken, email, password, callbackUrl: `${baseUrl}/checkout`, json: "true" }) }); cookies.push(...cookieValues(response)); assert(response.status === 200 || response.status === 302, `Login failed: ${response.status}`); assert(cookies.some((cookie) => /authjs\.session-token|next-auth\.session-token/.test(cookie)), "Session cookie missing."); return cookies.join("; "); }
async function json(cookie: string, path: string, method = "GET", body?: unknown) { const response = await fetch(`${baseUrl}${path}`, { method, headers: { ...(body ? { "Content-Type": "application/json" } : {}), Cookie: cookie }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json().catch(() => ({})); return { response, data: data as Record<string, unknown> }; }
function assertNoFinance(value: unknown) { const text = JSON.stringify(value); for (const field of ["commissionRate", "commissionAmount", "sellerNetAmount", "payout", "ledgerEntries"]) assert(!text.includes(`\"${field}\"`), `Customer finance leak: ${field}`); }

async function main() {
  if (process.argv.includes("--cleanup")) { await cleanup(); const remaining = await prisma.user.count({ where: { email: { startsWith: emailPrefix, endsWith: "@invalid.local" } } }); assert(remaining === 0, `QA cleanup left ${remaining} user(s).`); console.log("PASS: QA-SHIPPING cleanup completed; 0 fixture users remain."); return; }
  await cleanup(); const suffix = crypto.randomUUID().slice(0, 10); const hash = await bcrypt.hash(password, 12);
  try {
    const sellerA = await prisma.user.create({ data: { name: "QA", surname: "Seller A", email: `${emailPrefix}seller-a-${suffix}@invalid.local`, phone: "0000000000", passwordHash: hash, role: "SELLER", sellerProfile: { create: { storeName: `${prefix}Seller-A-${suffix}`, storeSlug: `qa-shipping-a-${suffix}`, companyType: "TEST", taxNumber: `QSA${suffix}`, taxOffice: "QA", city: "Ä°stanbul", address: "QA", description: "QA", status: "APPROVED" } } }, include: { sellerProfile: true } });
    const sellerB = await prisma.user.create({ data: { name: "QA", surname: "Seller B", email: `${emailPrefix}seller-b-${suffix}@invalid.local`, phone: "0000000000", passwordHash: hash, role: "SELLER", sellerProfile: { create: { storeName: `${prefix}Seller-B-${suffix}`, storeSlug: `qa-shipping-b-${suffix}`, companyType: "TEST", taxNumber: `QSB${suffix}`, taxOffice: "QA", city: "Ankara", address: "QA", description: "QA", status: "APPROVED" } } }, include: { sellerProfile: true } });
    const customerA = await prisma.user.create({ data: { name: "QA", surname: "Customer A", email: `${emailPrefix}customer-a-${suffix}@invalid.local`, phone: "0000000000", passwordHash: hash } });
    const customerB = await prisma.user.create({ data: { name: "QA", surname: "Customer B", email: `${emailPrefix}customer-b-${suffix}@invalid.local`, phone: "0000000000", passwordHash: hash } });
    const admin = await prisma.user.create({ data: { name: "QA", surname: "Admin", email: `${emailPrefix}admin-${suffix}@invalid.local`, phone: "0000000000", passwordHash: hash, role: "ADMIN" } });
    const productA = await prisma.product.create({ data: { sellerId: sellerA.sellerProfile!.id, name: `${prefix}Product-A`, sku: `QSA-${suffix}`, slug: `qa-shipping-product-a-${suffix}`, category: "Olta Makineleri", brand: "QA", price: 100, stock: 10, description: "QA", imageUrl: "/products/spin-olta-seti.jpg", active: true } });
    const productB = await prisma.product.create({ data: { sellerId: sellerB.sellerProfile!.id, name: `${prefix}Product-B`, sku: `QSB-${suffix}`, slug: `qa-shipping-product-b-${suffix}`, category: "Misinalar", brand: "QA", price: 50, stock: 10, description: "QA", imageUrl: "/products/spin-olta-seti.jpg", active: true } });
    const [cookieA, cookieB, customerACookie, customerBCookie] = await Promise.all([login(sellerA.email), login(sellerB.email), login(customerA.email), login(customerB.email)]);
    async function checkout() { const result = await json(customerBCookie, "/api/orders", "POST", { clientRequestId: crypto.randomUUID(), address: { recipientName: "QA Customer B", phone: "05000000000", city: "Ä°stanbul", district: "KadÄ±kÃ¶y", address: "QA shipping address", postalCode: "34000" }, items: [{ productId: productA.id, quantity: 1 }, { productId: productB.id, quantity: 1 }] }); assert(result.response.status === 201 && typeof result.data.id === "string", `Checkout failed: ${result.response.status}`); return result.data.id as string; }
    const orderId = await checkout();
    const createA = await json(cookieA, "/api/seller/shipments", "POST", { orderId }); const createB = await json(cookieB, "/api/seller/shipments", "POST", { orderId }); assert(createA.response.status === 201 && createB.response.status === 201, "Shipment create failed."); const shipmentA = createA.data.id as string; const shipmentB = createB.data.id as string;
    const duplicateA = await json(cookieA, "/api/seller/shipments", "POST", { orderId }); assert(duplicateA.data.id === shipmentA && await prisma.shipment.count({ where: { orderId, sellerId: sellerA.sellerProfile!.id } }) === 1, "Shipment create is not idempotent.");
    const beforeB = await prisma.shipment.findUniqueOrThrow({ where: { id: shipmentB }, include: { items: true } }); const idor = await json(cookieA, `/api/seller/shipments/${shipmentB}`, "PATCH", { status: "PREPARING" }); assert(idor.response.status === 404, `Seller shipment IDOR returned ${idor.response.status}`); const afterB = await prisma.shipment.findUniqueOrThrow({ where: { id: shipmentB }, include: { items: true } }); assert(JSON.stringify(beforeB) === JSON.stringify(afterB), "Seller B shipment changed after IDOR attempt.");
    const customerIdor = await json(customerACookie, `/api/orders/${orderId}`); assert(customerIdor.response.status === 404, `Customer IDOR returned ${customerIdor.response.status}`); assertNoFinance(customerIdor.data); assert(!JSON.stringify(customerIdor.data).includes("QA shipping address"), "Customer address leaked in IDOR response.");
    const customerList = await json(customerBCookie, "/api/orders"); const customerDetail = await json(customerBCookie, `/api/orders/${orderId}`); assert(customerList.response.ok && customerDetail.response.ok, "Customer order APIs failed."); assertNoFinance(customerList.data); assertNoFinance(customerDetail.data);
    for (const status of ["PREPARING", "READY_TO_SHIP"] as const) { const result = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status }); assert(result.response.ok, `${status} failed.`); }
    const missingTracking = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "SHIPPED" }); assert(missingTracking.response.status === 400, "SHIPPED accepted without carrier/tracking.");
    const malicious = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "SHIPPED", carrierCode: "javascript:alert(1)", trackingNumber: "<script>" }); assert(malicious.response.status === 400, "Malicious carrier/tracking accepted.");
    const shipped = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "SHIPPED", carrierCode: "YURTICI", trackingNumber: "QA-A-12345" }); assert(shipped.response.ok, "Valid SHIPPED failed."); const shippedAgain = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "SHIPPED", carrierCode: "YURTICI", trackingNumber: "QA-A-12345" }); assert(shippedAgain.response.ok && shippedAgain.data.idempotent === true, "Repeated SHIPPED is not idempotent."); assert(await prisma.notification.count({ where: { dedupeKey: `shipment:${shipmentA}:SHIPPED:customer` } }) === 1, "Duplicate SHIPPED notification created.");
    const prepB = await json(cookieB, `/api/seller/shipments/${shipmentB}`, "PATCH", { status: "PREPARING" }); assert(prepB.response.ok, "Seller B PREPARING failed."); const independent = await prisma.shipment.findMany({ where: { id: { in: [shipmentA, shipmentB] } }, select: { id: true, status: true } }); assert(independent.find((item) => item.id === shipmentA)?.status === "SHIPPED" && independent.find((item) => item.id === shipmentB)?.status === "PREPARING", "Independent package states failed.");
    const delivered = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "DELIVERED" }); assert(delivered.response.ok, "DELIVERED failed."); const invalidBack = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "PREPARING" }); assert(invalidBack.response.status === 409, "DELIVERED -> PREPARING was accepted."); assert(await prisma.notification.count({ where: { dedupeKey: `shipment:${shipmentA}:DELIVERED:customer` } }) === 1, "DELIVERED notification missing/duplicated.");
    const cancelOrderId = await checkout(); const cancelItem = await prisma.orderItem.findFirstOrThrow({ where: { orderId: cancelOrderId, sellerId: sellerA.sellerProfile!.id } }); const stockBefore = (await prisma.product.findUniqueOrThrow({ where: { id: productA.id } })).stock; const cancel1 = await json(customerBCookie, `/api/orders/items/${cancelItem.id}/actions`, "POST", { action: "CANCEL" }); const stockAfter = (await prisma.product.findUniqueOrThrow({ where: { id: productA.id } })).stock; const cancel2 = await json(customerBCookie, `/api/orders/items/${cancelItem.id}/actions`, "POST", { action: "CANCEL" }); const stockAfterAgain = (await prisma.product.findUniqueOrThrow({ where: { id: productA.id } })).stock; assert(cancel1.response.ok && cancel2.response.ok && stockAfter === stockBefore + 1 && stockAfterAgain === stockAfter, "Cancellation stock restore idempotency failed.");
    const shippedItem = await prisma.orderItem.findFirstOrThrow({ where: { orderId, sellerId: sellerA.sellerProfile!.id } }); const shippedCancel = await json(customerBCookie, `/api/orders/items/${shippedItem.id}/actions`, "POST", { action: "CANCEL" }); assert(shippedCancel.response.status === 409, "Shipped/delivered item cancellation accepted.");
    const browserOrderId = await checkout(); const browserA = await json(cookieA, "/api/seller/shipments", "POST", { orderId: browserOrderId }); const browserB = await json(cookieB, "/api/seller/shipments", "POST", { orderId: browserOrderId }); assert(browserA.response.status === 201 && browserB.response.status === 201, "Browser fixture shipment create failed."); await json(cookieB, `/api/seller/shipments/${browserB.data.id}`, "PATCH", { status: "PREPARING" });
    console.log(JSON.stringify({ ok: true, sellerAEmail: sellerA.email, customerBEmail: customerB.email, adminEmail: admin.email, browserOrderId, sellerAShipmentId: browserA.data.id, sellerBShipmentId: browserB.data.id }));
  } catch (error) { await cleanup(); throw error; }
}
main().catch((error) => { console.error("FAIL:", error instanceof Error ? error.message : error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
