import "dotenv/config";
import bcrypt from "bcryptjs";
import { readFileSync } from "node:fs";
import { createGuardedTestPrisma } from "./guarded-test-prisma";
import { processVerifiedPaymentEvent } from "../app/lib/payment-orchestrator";

function testLocalSecret(name: string) {
  try {
    const line = readFileSync(".env.test.local", "utf8").split(/\r?\n/).find((value) => new RegExp(`^\\s*(?:export\\s+)?${name}\\s*=`).test(value));
    if (!line) return "";
    const value = line.slice(line.indexOf("=") + 1).trim();
    return (value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'")) ? value.slice(1, -1) : value;
  } catch {
    return "";
  }
}
const password = process.env.QA_SHIPPING_PASSWORD ?? testLocalSecret("QA_SHIPPING_PASSWORD");
const baseUrl = process.env.QA_BASE_URL ?? "http://localhost:3000";
if (password.length < 8) throw new Error("QA runtime configuration is missing or does not meet Auth credentials policy.");
const prisma = createGuardedTestPrisma();
const prefix = "QA-SHIPPING-";
const emailPrefix = "qa-shipping-";
const fixtureUserIds: string[] = [];
function assert(value: unknown, message: string): asserts value { if (!value) throw new Error(message); }
function cookieValues(response: Response) { const headers = typeof response.headers.getSetCookie === "function" ? response.headers.getSetCookie() : [response.headers.get("set-cookie") ?? ""]; return headers.map((value) => value.split(";", 1)[0]).filter(Boolean); }
async function cleanup() { if (!fixtureUserIds.length) return; const ids = (values: string[]) => ({ id: { in: values } }); const users = await prisma.user.findMany({ where: ids(fixtureUserIds), select: { sellerProfile: { select: { id: true, products: { select: { id: true, catalogProductId: true } } } } } }); const sellerIds = users.flatMap((user) => user.sellerProfile ? [user.sellerProfile.id] : []); const productIds = users.flatMap((user) => user.sellerProfile?.products.map((product) => product.id) ?? []); const catalogIds = [...new Set(users.flatMap((user) => user.sellerProfile?.products.flatMap((product) => product.catalogProductId ? [product.catalogProductId] : []) ?? []))]; const orders = await prisma.order.findMany({ where: { userId: { in: fixtureUserIds } }, select: { id: true, shipments: { select: { id: true } }, refunds: { select: { id: true } } } }); const shipmentIds = orders.flatMap((order) => order.shipments.map((shipment) => shipment.id)); const refundIds = orders.flatMap((order) => order.refunds.map((refund) => refund.id)); if (shipmentIds.length) await prisma.shipment.deleteMany({ where: ids(shipmentIds) }); if (refundIds.length) await prisma.refund.deleteMany({ where: ids(refundIds) }); if (orders.length) await prisma.order.deleteMany({ where: ids(orders.map((order) => order.id)) }); if (sellerIds.length) { const offers = await prisma.sellerOffer.findMany({ where: { sellerId: { in: sellerIds } }, select: { id: true } }); const offerIds = offers.map((offer) => offer.id); if (offerIds.length) { const movements = await prisma.stockMovement.findMany({ where: { sellerOfferId: { in: offerIds } }, select: { id: true } }); if (movements.length) await prisma.stockMovement.deleteMany({ where: ids(movements.map((movement) => movement.id)) }); await prisma.sellerOffer.deleteMany({ where: ids(offerIds) }); } } if (productIds.length) await prisma.product.deleteMany({ where: ids(productIds) }); await prisma.user.deleteMany({ where: ids(fixtureUserIds) }); if (catalogIds.length) await prisma.catalogProduct.deleteMany({ where: ids(catalogIds) }); }
async function login(email: string) { const cookies: string[] = []; const csrfResponse = await fetch(`${baseUrl}/api/auth/csrf`); assert(csrfResponse.ok, "CSRF endpoint failed."); cookies.push(...cookieValues(csrfResponse)); const csrf = await csrfResponse.json() as { csrfToken?: string }; assert(csrf.csrfToken, "CSRF token missing."); const response = await fetch(`${baseUrl}/api/auth/callback/credentials`, { method: "POST", redirect: "manual", headers: { "Content-Type": "application/x-www-form-urlencoded", Cookie: cookies.join("; ") }, body: new URLSearchParams({ csrfToken: csrf.csrfToken, email, password, callbackUrl: `${baseUrl}/checkout`, json: "true" }) }); cookies.push(...cookieValues(response)); assert(response.status === 200 || response.status === 302, `Login failed: ${response.status}`); assert(cookies.some((cookie) => /authjs\.session-token|next-auth\.session-token/.test(cookie)), "Session cookie missing."); return cookies.join("; "); }
async function json(cookie: string, path: string, method = "GET", body?: unknown) { const response = await fetch(`${baseUrl}${path}`, { method, headers: { ...(body ? { "Content-Type": "application/json" } : {}), Cookie: cookie }, body: body ? JSON.stringify(body) : undefined }); const data = await response.json().catch(() => ({})); return { response, data: data as Record<string, unknown> }; }
function assertNoFinance(value: unknown) { const text = JSON.stringify(value); for (const field of ["commissionRate", "commissionAmount", "sellerNetAmount", "payout", "ledgerEntries"]) assert(!text.includes(`\"${field}\"`), `Customer finance leak: ${field}`); }

async function main() {
  await cleanup(); const suffix = crypto.randomUUID().slice(0, 10); const hash = await bcrypt.hash(password, 12);
  try {
    const sellerA = await prisma.user.create({ data: { name: "QA", surname: "Seller A", email: `${emailPrefix}seller-a-${suffix}@invalid.local`, phone: "0000000000", passwordHash: hash, role: "SELLER", sellerProfile: { create: { storeName: `${prefix}Seller-A-${suffix}`, storeSlug: `qa-shipping-a-${suffix}`, companyType: "TEST", taxNumber: `QSA${suffix}`, taxOffice: "QA", city: "Ä°stanbul", address: "QA", description: "QA", status: "APPROVED" } } }, include: { sellerProfile: true } });
    const sellerB = await prisma.user.create({ data: { name: "QA", surname: "Seller B", email: `${emailPrefix}seller-b-${suffix}@invalid.local`, phone: "0000000000", passwordHash: hash, role: "SELLER", sellerProfile: { create: { storeName: `${prefix}Seller-B-${suffix}`, storeSlug: `qa-shipping-b-${suffix}`, companyType: "TEST", taxNumber: `QSB${suffix}`, taxOffice: "QA", city: "Ankara", address: "QA", description: "QA", status: "APPROVED" } } }, include: { sellerProfile: true } });
    const customerA = await prisma.user.create({ data: { name: "QA", surname: "Customer A", email: `${emailPrefix}customer-a-${suffix}@invalid.local`, phone: "0000000000", passwordHash: hash } });
    const customerB = await prisma.user.create({ data: { name: "QA", surname: "Customer B", email: `${emailPrefix}customer-b-${suffix}@invalid.local`, phone: "0000000000", passwordHash: hash } });
    const admin = await prisma.user.create({ data: { name: "QA", surname: "Admin", email: `${emailPrefix}admin-${suffix}@invalid.local`, phone: "0000000000", passwordHash: hash, role: "ADMIN" } });
    fixtureUserIds.push(sellerA.id, sellerB.id, customerA.id, customerB.id, admin.id);
    const catalogA = await prisma.catalogProduct.create({ data: { slug: `qa-shipping-catalog-a-${suffix}`, identityKey: `QA-SHIPPING-A-${suffix}`, name: `${prefix}Product-A`, category: "Olta Makineleri", brand: "QA", description: "QA", imageUrl: "/products/spin-olta-seti.jpg" } });
    const catalogB = await prisma.catalogProduct.create({ data: { slug: `qa-shipping-catalog-b-${suffix}`, identityKey: `QA-SHIPPING-B-${suffix}`, name: `${prefix}Product-B`, category: "Misinalar", brand: "QA", description: "QA", imageUrl: "/products/spin-olta-seti.jpg" } });
    const productA = await prisma.product.create({ data: { sellerId: sellerA.sellerProfile!.id, catalogProductId: catalogA.id, name: `${prefix}Product-A`, sku: `QSA-${suffix}`, slug: `qa-shipping-product-a-${suffix}`, category: "Olta Makineleri", brand: "QA", price: 100, stock: 10, description: "QA", imageUrl: "/products/spin-olta-seti.jpg", active: true } });
    const productB = await prisma.product.create({ data: { sellerId: sellerB.sellerProfile!.id, catalogProductId: catalogB.id, name: `${prefix}Product-B`, sku: `QSB-${suffix}`, slug: `qa-shipping-product-b-${suffix}`, category: "Misinalar", brand: "QA", price: 50, stock: 10, description: "QA", imageUrl: "/products/spin-olta-seti.jpg", active: true } });
    await prisma.sellerOffer.createMany({ data: [{ sellerId: sellerA.sellerProfile!.id, catalogProductId: catalogA.id, legacyProductId: productA.id, sellerSku: `QSA-${suffix}`, price: 100, stock: 10 }, { sellerId: sellerB.sellerProfile!.id, catalogProductId: catalogB.id, legacyProductId: productB.id, sellerSku: `QSB-${suffix}`, price: 50, stock: 10 }] });
    const [cookieA, cookieB, customerACookie, customerBCookie] = await Promise.all([login(sellerA.email), login(sellerB.email), login(customerA.email), login(customerB.email)]);
    async function checkout() { const result = await json(customerBCookie, "/api/orders", "POST", { clientRequestId: crypto.randomUUID(), address: { recipientName: "QA Customer B", phone: "05000000000", city: "Ä°stanbul", district: "KadÄ±kÃ¶y", address: "QA shipping address", postalCode: "34000" }, items: [{ productId: productA.id, quantity: 1 }, { productId: productB.id, quantity: 1 }] }); assert(result.response.status === 201 && typeof result.data.id === "string", `Checkout failed: ${result.response.status}`); const orderId = result.data.id as string; const payment = await prisma.payment.findUniqueOrThrow({ where: { orderId } }); const paymentEventId = `qa-shipping-paid-${crypto.randomUUID()}`; await prisma.$transaction((tx) => processVerifiedPaymentEvent(tx, { provider: "TEST", event: { eventId: paymentEventId, paymentId: payment.id, eventType: "PAYMENT_PAID", amount: payment.amount.toString(), currency: payment.currency, providerPaymentId: `qa-shipping-provider-${paymentEventId}` }, payloadHash: paymentEventId })); return orderId; }
    const orderId = await checkout();
    const createA = await json(cookieA, "/api/seller/shipments", "POST", { orderId }); const createB = await json(cookieB, "/api/seller/shipments", "POST", { orderId }); assert(createA.response.status === 201 && createB.response.status === 201, "Shipment create failed."); const shipmentA = createA.data.id as string; const shipmentB = createB.data.id as string;
    const duplicateA = await json(cookieA, "/api/seller/shipments", "POST", { orderId }); assert(duplicateA.data.id === shipmentA && await prisma.shipment.count({ where: { orderId, sellerId: sellerA.sellerProfile!.id } }) === 1, "Shipment create is not idempotent.");
    const beforeB = await prisma.shipment.findUniqueOrThrow({ where: { id: shipmentB }, include: { items: true } }); const idor = await json(cookieA, `/api/seller/shipments/${shipmentB}`, "PATCH", { status: "PREPARING" }); assert(idor.response.status === 404, `Seller shipment IDOR returned ${idor.response.status}`); const afterB = await prisma.shipment.findUniqueOrThrow({ where: { id: shipmentB }, include: { items: true } }); assert(JSON.stringify(beforeB) === JSON.stringify(afterB), "Seller B shipment changed after IDOR attempt.");
    const customerIdor = await json(customerACookie, `/api/orders/${orderId}`); assert(customerIdor.response.status === 404, `Customer IDOR returned ${customerIdor.response.status}`); assertNoFinance(customerIdor.data); assert(!JSON.stringify(customerIdor.data).includes("QA shipping address"), "Customer address leaked in IDOR response.");
    const customerList = await json(customerBCookie, "/api/orders"); const customerDetail = await json(customerBCookie, `/api/orders/${orderId}`); assert(customerList.response.ok && customerDetail.response.ok, "Customer order APIs failed."); assertNoFinance(customerList.data); assertNoFinance(customerDetail.data);
    for (const status of ["PREPARING", "READY_TO_SHIP"] as const) { const result = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status }); assert(result.response.ok, `${status} failed.`); }
    const missingTracking = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "SHIPPED" }); assert(missingTracking.response.status === 400, "SHIPPED accepted without carrier/tracking.");
    const malicious = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "SHIPPED", carrierCode: "javascript:alert(1)", trackingNumber: "<script>" }); assert(malicious.response.status === 400, "Malicious carrier/tracking accepted.");
    const shipped = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "SHIPPED", carrierCode: "YURTICI", trackingNumber: "QA-A-12345" }); assert(shipped.response.ok, "Valid SHIPPED failed."); const shippedAgain = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "SHIPPED", carrierCode: "YURTICI", trackingNumber: "QA-A-12345" }); assert(shippedAgain.response.ok && shippedAgain.data.idempotent === true, "Repeated SHIPPED is not idempotent."); assert(await prisma.notification.count({ where: { dedupeKey: `shipment:${shipmentA}:SHIPPED:customer` } }) === 1, "Duplicate SHIPPED notification created.");
    const prepB = await json(cookieB, `/api/seller/shipments/${shipmentB}`, "PATCH", { status: "PREPARING" }); assert(prepB.response.ok, "Seller B PREPARING failed."); const independent = await prisma.shipment.findMany({ where: { id: { in: [shipmentA, shipmentB] } }, select: { id: true, status: true } }); assert(independent.find((item) => item.id === shipmentA)?.status === "SHIPPED" && independent.find((item) => item.id === shipmentB)?.status === "PREPARING", "Independent package states failed.");
    const delivered = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "DELIVERED" }); assert(delivered.response.ok, "DELIVERED failed."); const invalidBack = await json(cookieA, `/api/seller/shipments/${shipmentA}`, "PATCH", { status: "PREPARING" }); assert(invalidBack.response.status === 409, "DELIVERED -> PREPARING was accepted."); assert(await prisma.notification.count({ where: { dedupeKey: `shipment:${shipmentA}:DELIVERED:customer` } }) === 1, "DELIVERED notification missing/duplicated.");
    const cancelOrderId = await checkout(); const cancelItem = await prisma.orderItem.findFirstOrThrow({ where: { orderId: cancelOrderId, sellerId: sellerA.sellerProfile!.id } }); const offerA = await prisma.sellerOffer.findFirstOrThrow({ where: { sellerId: sellerA.sellerProfile!.id, legacyProductId: productA.id } }); const stockBefore = offerA.stock; const cancel1 = await json(customerBCookie, `/api/orders/items/${cancelItem.id}/actions`, "POST", { action: "CANCEL" }); const stockAfter = (await prisma.sellerOffer.findUniqueOrThrow({ where: { id: offerA.id } })).stock; const releasesAfterFirst = await prisma.stockMovement.count({ where: { orderItemId: cancelItem.id, sellerOfferId: offerA.id, type: "RESERVATION_RELEASE" } }); const cancel2 = await json(customerBCookie, `/api/orders/items/${cancelItem.id}/actions`, "POST", { action: "CANCEL" }); const stockAfterAgain = (await prisma.sellerOffer.findUniqueOrThrow({ where: { id: offerA.id } })).stock; const releasesAfterReplay = await prisma.stockMovement.count({ where: { orderItemId: cancelItem.id, sellerOfferId: offerA.id, type: "RESERVATION_RELEASE" } }); assert(cancel1.response.ok && cancel2.response.ok && stockAfter === stockBefore + cancelItem.quantity && stockAfterAgain === stockAfter && releasesAfterFirst === 1 && releasesAfterReplay === 1, "Cancellation SellerOffer reservation release idempotency failed.");
    const shippedItem = await prisma.orderItem.findFirstOrThrow({ where: { orderId, sellerId: sellerA.sellerProfile!.id } }); const shippedCancel = await json(customerBCookie, `/api/orders/items/${shippedItem.id}/actions`, "POST", { action: "CANCEL" }); assert(shippedCancel.response.status === 409, "Shipped/delivered item cancellation accepted.");
    const browserOrderId = await checkout(); const browserA = await json(cookieA, "/api/seller/shipments", "POST", { orderId: browserOrderId }); const browserB = await json(cookieB, "/api/seller/shipments", "POST", { orderId: browserOrderId }); assert(browserA.response.status === 201 && browserB.response.status === 201, "Browser fixture shipment create failed."); await json(cookieB, `/api/seller/shipments/${browserB.data.id}`, "PATCH", { status: "PREPARING" });
    console.log("PASS: guarded shipping runtime payment gate, seller/customer isolation, transitions, cancellation and replay verified.");
  } finally { await cleanup(); }
}
main().catch((error) => { console.error("FAIL:", error instanceof Error ? error.message : error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
